"""Seed data for the Only Good Things self-care activity catalog."""

import os

import db

ACTIVITIES = [
    # ── Body (8) ──
    {
        "name": "Morning Stretch Ritual",
        "category": "body",
        "tagline": "Greet the day with your whole body",
        "description": "A gentle 15-minute sequence of stretches designed to wake up your muscles and joints. Move slowly, breathe deeply, and let your body unfold at its own pace.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Yoga mat or soft rug, comfortable clothes",
        "instructions": "1. Stand tall and reach your arms overhead, stretching side to side.\n2. Fold forward gently, letting your head hang heavy.\n3. Come to hands and knees for cat-cow stretches, 5 rounds.\n4. Sit cross-legged and twist gently to each side.\n5. Lie on your back and hug your knees to your chest.",
        "benefit": "energy",
        "moon_phase": "any",
    },
    {
        "name": "Dry Brushing",
        "category": "body",
        "tagline": "Sweep away what no longer serves you",
        "description": "An ancient practice of brushing dry skin with a natural bristle brush to boost circulation and slough off dead skin. A small act that makes your whole body hum.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Natural bristle dry brush",
        "instructions": "1. Start at your feet with long, sweeping strokes toward your heart.\n2. Move up your legs, using firm but gentle pressure.\n3. Brush your arms from fingertips toward shoulders.\n4. Use gentle circular motions on your stomach.\n5. Follow with a warm shower and moisturizer.",
        "benefit": "energy",
        "moon_phase": "waning",
    },
    {
        "name": "Warm Bath Soak",
        "category": "body",
        "tagline": "Dissolve the day in warm water",
        "description": "A slow, intentional bath with salts or oils. Light a candle, put your phone away, and let the warm water hold you. This is not about getting clean — it's about getting quiet.",
        "duration_min": 45,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Epsom salt or bath oil, candle, towel",
        "instructions": "1. Run a warm bath and add a generous handful of Epsom salt or a few drops of essential oil.\n2. Light a candle and dim the overhead lights.\n3. Set your phone in another room.\n4. Soak for at least 20 minutes, breathing deeply.\n5. Pat dry gently and apply body oil while skin is still damp.",
        "benefit": "stress",
        "moon_phase": "full",
    },
    {
        "name": "Face Massage with Oil",
        "category": "body",
        "tagline": "Tend to the face you show the world",
        "description": "A nurturing facial massage using a natural oil like jojoba or rosehip. Releases tension held in the jaw, brow, and temples — places where we store more than we realize.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Facial oil (jojoba, rosehip, or argan), clean hands",
        "instructions": "1. Warm a few drops of oil between your palms.\n2. Press palms gently against your face, holding for a breath.\n3. Use fingertips to make small circles along the jawline.\n4. Smooth across the forehead from center to temples.\n5. Finish with gentle pressure on the temples, holding for five breaths.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Scalp Massage",
        "category": "body",
        "tagline": "Unwind from the top down",
        "description": "A deeply relaxing self-massage focused on the scalp, where we hold surprising amounts of tension. Use your fingertips or a simple scalp massager for an instant calm.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Scalp massager (optional), hair oil (optional)",
        "instructions": "1. Sit comfortably and close your eyes.\n2. Place all ten fingertips on your scalp.\n3. Make small, firm circles, starting at the hairline.\n4. Work slowly toward the crown and down to the nape.\n5. Spend extra time on any spots that feel tender or tight.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Walking Meditation",
        "category": "body",
        "tagline": "Each step is its own arrival",
        "description": "A practice of walking slowly and deliberately, paying attention to the sensation of each footfall. Not about getting somewhere — about being fully here with each step.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "either",
        "supplies": "Comfortable shoes, a quiet path",
        "instructions": "1. Stand still for a moment, feeling your weight on the earth.\n2. Begin walking very slowly, noticing the lift, swing, and placement of each foot.\n3. Let your arms hang naturally at your sides.\n4. When your mind wanders, gently bring attention back to the soles of your feet.\n5. Walk for 10-20 minutes, then stand still again before resuming normal pace.",
        "benefit": "focus",
        "moon_phase": "any",
    },
    {
        "name": "Gentle Yoga Flow",
        "category": "body",
        "tagline": "Move like water, not like a machine",
        "description": "A slow, breath-linked yoga sequence focused on ease rather than achievement. No perfect poses — just your body, your breath, and the space between them.",
        "duration_min": 30,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Yoga mat, blocks (optional), blanket",
        "instructions": "1. Begin in child's pose, breathing deeply for one minute.\n2. Move through 5 slow sun salutations, pausing in each shape.\n3. Hold warrior II on each side for 5 breaths.\n4. Flow through pigeon pose on each side, staying for 10 breaths.\n5. End in savasana for at least 3 minutes.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Cold Plunge Breathing",
        "category": "body",
        "tagline": "Meet the cold and find your calm",
        "description": "A breathwork practice paired with cold water exposure — even just turning the shower cold for the final 30 seconds. Builds resilience and floods the body with aliveness.",
        "duration_min": 10,
        "difficulty": "involved",
        "season": "all",
        "setting": "indoor",
        "supplies": "Shower or cold water access, towel",
        "instructions": "1. Take 30 deep breaths — in through the nose, out through the mouth.\n2. Hold your breath after the last exhale for as long as comfortable.\n3. Take one deep recovery breath and hold for 15 seconds.\n4. Repeat the breathing cycle two more times.\n5. Turn the shower to cold for 30-60 seconds, breathing steadily.",
        "benefit": "energy",
        "moon_phase": "new",
    },

    # ── Mind (8) ──
    {
        "name": "Journaling Prompts",
        "category": "mind",
        "tagline": "Let the pen find what the mind hides",
        "description": "Guided freewriting using a single prompt to unlock thoughts you didn't know you were carrying. Not about beautiful writing — about honest writing.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Notebook, pen",
        "instructions": "1. Choose a prompt: 'What am I avoiding?' or 'What would I do if no one was watching?'\n2. Set a timer for 15 minutes.\n3. Write without stopping — don't edit, don't reread.\n4. If you get stuck, write 'I'm stuck' until something else comes.\n5. When the timer ends, close the notebook without rereading.",
        "benefit": "focus",
        "moon_phase": "new",
    },
    {
        "name": "Guided Meditation",
        "category": "mind",
        "tagline": "Borrow someone else's calm for a while",
        "description": "A led meditation practice using an app or recording. Let someone else do the thinking while you simply follow along. Perfect for days when your own mind is too loud.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Phone or speaker, meditation app or recording, cushion",
        "instructions": "1. Find a quiet space and sit or lie down comfortably.\n2. Choose a guided meditation (body scan, loving-kindness, or breath focus).\n3. Press play and close your eyes.\n4. Follow the guide's instructions without judging your experience.\n5. When it ends, sit quietly for one more minute before moving.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Box Breathing",
        "category": "mind",
        "tagline": "Four sides of a single breath",
        "description": "A structured breathing technique used by Navy SEALs and monks alike. Inhale, hold, exhale, hold — each for the same count. Remarkably effective at calming the nervous system.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "either",
        "supplies": "None — just yourself",
        "instructions": "1. Sit upright with your feet flat on the floor.\n2. Inhale slowly through your nose for 4 counts.\n3. Hold your breath for 4 counts.\n4. Exhale slowly through your mouth for 4 counts.\n5. Hold empty for 4 counts. Repeat for 5-10 minutes.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Digital Detox Hour",
        "category": "mind",
        "tagline": "An hour without the glow",
        "description": "One full hour with all screens turned off. Not hidden — turned off. Rediscover what your hands and eyes do when they're not scrolling. It's stranger and lovelier than you'd expect.",
        "duration_min": 60,
        "difficulty": "moderate",
        "season": "all",
        "setting": "either",
        "supplies": "A book, sketchpad, or nothing at all",
        "instructions": "1. Set a timer on a non-screen device (kitchen timer, watch).\n2. Power off or place all screens in a drawer.\n3. Resist the urge to check — notice the impulse and let it pass.\n4. Do whatever calls to you: read, draw, sit, walk, cook.\n5. When the hour ends, notice how you feel before turning anything back on.",
        "benefit": "focus",
        "moon_phase": "full",
    },
    {
        "name": "Gratitude List",
        "category": "mind",
        "tagline": "Count what counts",
        "description": "Writing down five specific things you're grateful for today. Not big, abstract things — small, real ones. The warmth of your coffee. A text from a friend. The way light hit the wall.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Notebook, pen",
        "instructions": "1. Sit quietly and close your eyes for a moment.\n2. Think about the last 24 hours.\n3. Write down 5 specific things you're grateful for — be detailed.\n4. For each one, write why it matters to you.\n5. Read the list back to yourself slowly.",
        "benefit": "joy",
        "moon_phase": "full",
    },
    {
        "name": "Brain Dump Writing",
        "category": "mind",
        "tagline": "Empty the jar so it can fill again",
        "description": "Pouring every thought, worry, task, and half-idea out of your head and onto paper. Not organized, not prioritized — just out. The relief is immediate and real.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Large blank paper or notebook, pen",
        "instructions": "1. Get a large piece of paper — bigger than usual.\n2. Set a timer for 10 minutes.\n3. Write down everything in your head: tasks, worries, ideas, names, feelings.\n4. Don't organize — just dump. Use arrows, circles, margins.\n5. When done, circle the 3 most important items. Let the rest wait.",
        "benefit": "focus",
        "moon_phase": "waning",
    },
    {
        "name": "Mindful Tea Ceremony",
        "category": "mind",
        "tagline": "One cup, made with your whole attention",
        "description": "Making and drinking a single cup of tea with complete presence. Hear the water boil, watch the color bloom, feel the warmth in your hands. A tiny ceremony that resets the day.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Loose leaf tea or tea bag, kettle, favorite cup",
        "instructions": "1. Fill the kettle and listen to the water begin to heat.\n2. Choose your tea with intention — what does today call for?\n3. Pour the water slowly and watch the color change.\n4. Hold the cup with both hands and breathe in the steam.\n5. Drink slowly, tasting each sip as if it were the first.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Body Scan Meditation",
        "category": "mind",
        "tagline": "Visit every room in the house of your body",
        "description": "A systematic meditation that moves attention slowly from head to toes (or toes to head), noticing sensations without trying to change them. Deeply grounding and quietly revelatory.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Comfortable surface to lie on, blanket",
        "instructions": "1. Lie down on your back with arms at your sides.\n2. Close your eyes and take five deep breaths.\n3. Bring attention to the top of your head, then slowly move down.\n4. Notice each area without judgment: forehead, jaw, neck, shoulders, and so on.\n5. When you reach your toes, take three deep breaths and slowly open your eyes.",
        "benefit": "sleep",
        "moon_phase": "full",
    },

    # ── Creative (8) ──
    {
        "name": "Watercolor Painting",
        "category": "creative",
        "tagline": "Let the water lead",
        "description": "Loose, intuitive watercolor painting — not about making something perfect, but about watching color move through water. The medium teaches you to let go of control.",
        "duration_min": 45,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Watercolor set, brushes, watercolor paper, water cup, rag",
        "instructions": "1. Wet your paper with clean water using a large brush.\n2. Choose 2-3 colors that feel right today.\n3. Touch the wet paper with loaded brush and watch the color bloom.\n4. Add more color or water, letting shapes emerge on their own.\n5. Let it dry completely. Name it something unexpected.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Collage Making",
        "category": "creative",
        "tagline": "Rearrange the world on paper",
        "description": "Cutting and arranging images from magazines, old books, or printed photos into something new. A tactile, low-pressure creative practice that lets your subconscious do the composing.",
        "duration_min": 60,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Old magazines or printed images, scissors, glue stick, cardstock",
        "instructions": "1. Gather a stack of magazines or printed images.\n2. Flip through and tear out anything that catches your eye — don't overthink it.\n3. Cut out shapes, words, textures that appeal to you.\n4. Arrange pieces on cardstock, moving them around until something clicks.\n5. Glue down and let it be what it is.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Poetry Writing",
        "category": "creative",
        "tagline": "Say the unsayable in fewer words",
        "description": "Writing a short poem — even just three lines. Poetry isn't about rhyming or rules; it's about paying close enough attention that language becomes a window.",
        "duration_min": 30,
        "difficulty": "moderate",
        "season": "all",
        "setting": "either",
        "supplies": "Notebook, pen",
        "instructions": "1. Look around you and choose one small thing to describe.\n2. Write three specific details about it — what does it look like, sound like, feel like?\n3. Arrange those details into lines, cutting unnecessary words.\n4. Read it aloud — does it sound like you?\n5. Give it a title that surprises you.",
        "benefit": "focus",
        "moon_phase": "new",
    },
    {
        "name": "Playlist Curation",
        "category": "creative",
        "tagline": "Score the soundtrack to a feeling",
        "description": "Building a playlist with intention — not shuffling, but choosing each song for a mood, a memory, or a moment. A creative act disguised as something ordinary.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Music streaming app, headphones",
        "instructions": "1. Choose a theme: a season, a feeling, a person, a time of day.\n2. Pick an opening track that sets the tone.\n3. Build the arc — let each song flow into the next.\n4. Aim for 10-15 songs, about 45 minutes.\n5. Name the playlist something only you'd understand.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Flower Arranging",
        "category": "creative",
        "tagline": "Bring the outside in, stem by stem",
        "description": "Arranging flowers — from a market bouquet or even roadside wildflowers — into a vase with intention. A practice in color, balance, and impermanence.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "spring",
        "setting": "indoor",
        "supplies": "Flowers (fresh or foraged), vase, scissors or garden shears",
        "instructions": "1. Gather your flowers and trim stems at an angle under water.\n2. Remove any leaves that will sit below the waterline.\n3. Start with your largest stems as the structure.\n4. Fill in with smaller blooms and greenery, turning the vase as you go.\n5. Place somewhere you'll see it often. Notice it change over the days.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Hand Lettering Practice",
        "category": "creative",
        "tagline": "Slow down to the speed of ink",
        "description": "Practicing beautiful letterforms with a pen or brush marker. Not about perfection — about the meditative rhythm of forming each letter with care and attention.",
        "duration_min": 30,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Brush pen or felt-tip marker, practice paper or dot grid notebook",
        "instructions": "1. Choose a word or short phrase that means something to you.\n2. Practice the basic strokes: thin upstrokes, thick downstrokes.\n3. Write the word slowly, focusing on each letter.\n4. Try it three different ways — larger, smaller, different spacing.\n5. Choose your favorite version and trace it with intention.",
        "benefit": "focus",
        "moon_phase": "any",
    },
    {
        "name": "Photography Walk",
        "category": "creative",
        "tagline": "See your world as if for the first time",
        "description": "A walk with the sole purpose of taking photographs — with your phone or a camera. Constraints help: only shoot shadows, or only red things, or only textures. Seeing changes when you look with purpose.",
        "duration_min": 45,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "Camera or phone, comfortable shoes",
        "instructions": "1. Choose a constraint: one color, one shape, or one theme (doors, light, hands).\n2. Walk your neighborhood with fresh eyes.\n3. Take at least 20 photos — don't be precious about them.\n4. Stop when something surprises you and really look before shooting.\n5. Choose 3 favorites and consider why they stand out.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Mending & Visible Repair",
        "category": "creative",
        "tagline": "Honor the tear instead of hiding it",
        "description": "Repairing a garment using visible stitching or patching — inspired by the Japanese philosophy of kintsugi. The mend becomes a feature, not a flaw. A meditation on imperfection.",
        "duration_min": 45,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Garment to mend, embroidery thread, needle, fabric scraps (optional)",
        "instructions": "1. Choose a garment with a tear, hole, or worn spot.\n2. Select thread in a contrasting color — the repair should be seen.\n3. Use a running stitch, sashiko pattern, or simple patch.\n4. Work slowly, enjoying the repetitive motion of the needle.\n5. Wear the mended garment with pride.",
        "benefit": "focus",
        "moon_phase": "waxing",
    },

    # ── Nature (7) ──
    {
        "name": "Forest Bathing",
        "category": "nature",
        "tagline": "Let the trees hold you for a while",
        "description": "Shinrin-yoku — the Japanese practice of immersing yourself in the forest atmosphere. Not hiking, not exercising — just being among trees. Research shows it lowers cortisol, blood pressure, and heart rate.",
        "duration_min": 60,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "Comfortable shoes, layers for weather",
        "instructions": "1. Find a wooded area — even a large park with mature trees.\n2. Leave your phone in your pocket or bag.\n3. Walk very slowly, with no destination.\n4. Engage all senses: touch bark, smell earth, listen for birds.\n5. Find a spot to sit for 10 minutes, just breathing and being.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Cloud Watching",
        "category": "nature",
        "tagline": "The sky's slow cinema",
        "description": "Lying on your back and watching clouds — genuinely, deliberately, like it matters. Because it does. There is no faster way to remember how large the world is and how small your worries are.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "summer",
        "setting": "outdoor",
        "supplies": "Blanket, open sky",
        "instructions": "1. Find an open spot with a wide view of the sky.\n2. Spread a blanket and lie on your back.\n3. Let your eyes soften and take in the whole sky.\n4. Watch individual clouds — notice their shapes, speed, and layers.\n5. Stay for at least 15 minutes. Let yourself do absolutely nothing else.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Herb Garden Tending",
        "category": "nature",
        "tagline": "Grow something you can taste",
        "description": "Caring for a small herb garden — even just a few pots on a windowsill. Watering, pruning, harvesting. The simplest form of nurturing something alive.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "spring",
        "setting": "either",
        "supplies": "Herb pots (basil, mint, rosemary), watering can, small scissors",
        "instructions": "1. Check soil moisture — water if the top inch is dry.\n2. Pinch off any dead or yellowing leaves.\n3. Harvest a few leaves for cooking or tea.\n4. Turn pots so all sides get sunlight.\n5. Talk to them if you want. Plants don't judge.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Sunrise or Sunset Watching",
        "category": "nature",
        "tagline": "Witness the world turning",
        "description": "Sitting still to watch the sun rise or set — the full show, from first color to last. No photos required. Just your eyes, the horizon, and the ancient slow spectacle of light.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "Warm layers, a good vantage point, a warm drink (optional)",
        "instructions": "1. Check the time for sunrise or sunset in your area.\n2. Arrive 15 minutes early to settle in.\n3. Find a comfortable spot with a clear view of the horizon.\n4. Put your phone away and just watch.\n5. Stay until the color has fully faded. Notice the afterglow.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Night Sky Stargazing",
        "category": "nature",
        "tagline": "Remember you are made of the same stuff",
        "description": "Spending time under the night sky, looking up. Learn one constellation, or learn none — just look. The dark and the distance have a way of putting things in perspective.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "winter",
        "setting": "outdoor",
        "supplies": "Blanket or chair, warm layers, star chart app (optional)",
        "instructions": "1. Find the darkest spot you can — away from streetlights.\n2. Give your eyes 10 minutes to adjust to the dark.\n3. Look for familiar patterns — the Big Dipper, Orion's Belt.\n4. Try to spot a planet (they don't twinkle like stars).\n5. Lie back and let the scale of it sink in.",
        "benefit": "stress",
        "moon_phase": "new",
    },
    {
        "name": "Foraging Walk",
        "category": "nature",
        "tagline": "The earth sets a table if you know where to look",
        "description": "A walk with the intention of identifying and gathering wild edibles — herbs, berries, mushrooms. Always with proper identification and respect for the ecosystem.",
        "duration_min": 60,
        "difficulty": "involved",
        "season": "fall",
        "setting": "outdoor",
        "supplies": "Field guide or foraging app, basket or bag, gloves",
        "instructions": "1. Research what's in season in your area before heading out.\n2. Bring a reliable field guide — never eat anything you're unsure about.\n3. Walk slowly, scanning the ground and lower branches.\n4. Harvest only what you'll use, and never take more than a third of any patch.\n5. At home, clean and prepare your finds with gratitude.",
        "benefit": "joy",
        "moon_phase": "full",
    },
    {
        "name": "Bird Watching",
        "category": "nature",
        "tagline": "Learn the names of your neighbors",
        "description": "Sitting quietly and watching birds — in your yard, a park, or anywhere outdoors. Once you start noticing, the world fills with wings. A practice in patience and attention.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "spring",
        "setting": "outdoor",
        "supplies": "Binoculars (optional), bird identification app or field guide, notebook",
        "instructions": "1. Find a quiet spot outdoors and sit still.\n2. Listen first — most birds are heard before they're seen.\n3. When you spot one, notice its size, color, and movement patterns.\n4. Try to identify it using your guide or app.\n5. Keep a simple list of what you see — it becomes a journal over time.",
        "benefit": "focus",
        "moon_phase": "any",
    },

    # ── Nourish (7) ──
    {
        "name": "Slow-Cooked Soup",
        "category": "nourish",
        "tagline": "Let time be the main ingredient",
        "description": "Making a soup from scratch, slowly — chopping vegetables, building flavor, letting it simmer for as long as it needs. The kitchen fills with warmth and the house smells like home.",
        "duration_min": 90,
        "difficulty": "moderate",
        "season": "fall",
        "setting": "indoor",
        "supplies": "Fresh vegetables, broth, herbs, heavy pot, cutting board, knife",
        "instructions": "1. Choose your base: onion, garlic, celery, carrot — dice them small.\n2. Sauté the base in olive oil until soft and fragrant.\n3. Add your main vegetables and broth, bring to a gentle simmer.\n4. Season with herbs (thyme, bay leaf, black pepper) and let it cook low and slow.\n5. Taste, adjust, and serve in a bowl you love.",
        "benefit": "connection",
        "moon_phase": "full",
    },
    {
        "name": "Herbal Tea Blending",
        "category": "nourish",
        "tagline": "Compose a cup that's entirely yours",
        "description": "Creating your own tea blend from dried herbs, flowers, and spices. Chamomile and lavender for calm, ginger and lemon for energy — you become the herbalist.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Dried herbs (chamomile, lavender, peppermint, ginger), small jars, tea infuser",
        "instructions": "1. Choose a purpose for your blend: calm, energy, digestion, or warmth.\n2. Select 2-3 base herbs and one accent flavor.\n3. Mix in a small bowl, smelling as you go.\n4. Store in a labeled jar with the date.\n5. Brew a test cup and adjust ratios for next time.",
        "benefit": "joy",
        "moon_phase": "new",
    },
    {
        "name": "Bread Baking",
        "category": "nourish",
        "tagline": "Flour, water, salt, time, and your hands",
        "description": "Baking a simple loaf of bread from scratch. The kneading is meditative, the waiting is a practice in patience, and the smell of fresh bread is its own reward.",
        "duration_min": 180,
        "difficulty": "involved",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Flour, water, yeast, salt, mixing bowl, baking sheet or Dutch oven",
        "instructions": "1. Mix flour, water, yeast, and salt into a shaggy dough.\n2. Knead for 10 minutes until smooth and elastic.\n3. Cover and let rise in a warm spot for 1-2 hours.\n4. Shape the dough, place in a floured vessel, and let rise again.\n5. Bake in a preheated oven (450°F) until golden and hollow-sounding when tapped.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Seasonal Fruit Preserving",
        "category": "nourish",
        "tagline": "Capture summer in a jar",
        "description": "Making a simple jam or preserve from seasonal fruit. Strawberries in June, peaches in August, figs in September. A way to hold onto a season long after it passes.",
        "duration_min": 60,
        "difficulty": "moderate",
        "season": "summer",
        "setting": "indoor",
        "supplies": "Fresh fruit, sugar, lemon juice, heavy-bottomed pot, glass jars",
        "instructions": "1. Wash and chop your fruit, removing any stems or pits.\n2. Combine fruit, sugar, and lemon juice in a heavy pot.\n3. Cook on medium heat, stirring often, until thick and jammy (20-30 min).\n4. Test for set by placing a spoonful on a cold plate.\n5. Pour into sterilized jars and seal while hot.",
        "benefit": "joy",
        "moon_phase": "full",
    },
    {
        "name": "Meal Prep Sunday",
        "category": "nourish",
        "tagline": "A gift from today-you to tomorrow-you",
        "description": "Spending a few hours on Sunday preparing meals for the week ahead. Chopping, roasting, portioning. Future-you will be grateful every single time.",
        "duration_min": 120,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Groceries for the week, containers, cutting board, sheet pans",
        "instructions": "1. Plan 3-4 meals for the week and make a grocery list.\n2. Start with items that take longest: grains, roasted vegetables, proteins.\n3. While those cook, prep raw ingredients: wash greens, chop vegetables.\n4. Portion meals into containers, labeling with contents and date.\n5. Stack in the fridge and admire your future self's good fortune.",
        "benefit": "energy",
        "moon_phase": "waxing",
    },
    {
        "name": "Farmers Market Visit",
        "category": "nourish",
        "tagline": "Let the season choose your menu",
        "description": "Visiting a farmers market with no list — just open eyes and curiosity. Let whatever is freshest and most beautiful guide your meals for the week.",
        "duration_min": 60,
        "difficulty": "easy",
        "season": "summer",
        "setting": "outdoor",
        "supplies": "Reusable bags, cash, a good appetite for wandering",
        "instructions": "1. Arrive early for the best selection.\n2. Walk the entire market once before buying anything.\n3. Talk to the growers — ask what's at peak season.\n4. Buy one thing you've never cooked before.\n5. Plan the week's meals around what you brought home.",
        "benefit": "connection",
        "moon_phase": "any",
    },
    {
        "name": "Infused Water Crafting",
        "category": "nourish",
        "tagline": "Make hydration a small ceremony",
        "description": "Creating beautiful, flavorful infused water with fresh fruits, herbs, and edible flowers. A gentle way to drink more water and add a touch of beauty to the everyday.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "summer",
        "setting": "indoor",
        "supplies": "Glass pitcher, fresh fruit (citrus, berries), fresh herbs (mint, basil), ice",
        "instructions": "1. Choose a combination: cucumber-mint, strawberry-basil, or citrus-rosemary.\n2. Slice fruits and gently bruise herbs to release oils.\n3. Layer in a glass pitcher with ice.\n4. Fill with cold water and refrigerate for at least 30 minutes.\n5. Pour into your favorite glass and notice how much prettier water can be.",
        "benefit": "energy",
        "moon_phase": "any",
    },

    # ── Rest (7) ──
    {
        "name": "Sleep Hygiene Ritual",
        "category": "rest",
        "tagline": "Teach your body the language of sleep",
        "description": "A consistent pre-sleep routine that signals to your nervous system that it's time to wind down. The same steps, the same order, every night. Ritual creates safety, and safety creates sleep.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Dim lighting, herbal tea, book, comfortable sleepwear",
        "instructions": "1. Set a consistent wind-down time — same time each night.\n2. Dim all lights and switch to warm, low lighting.\n3. Make a cup of caffeine-free tea (chamomile, valerian, or rooibos).\n4. Read a physical book for 15-20 minutes (no screens).\n5. Do a 2-minute body scan in bed before closing your eyes.",
        "benefit": "sleep",
        "moon_phase": "any",
    },
    {
        "name": "Power Nap Protocol",
        "category": "rest",
        "tagline": "Twenty minutes of borrowed night",
        "description": "A strategic 20-minute nap taken between 1-3 PM — long enough to restore alertness, short enough to avoid sleep inertia. A small surrender that yields big returns.",
        "duration_min": 25,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Couch or bed, blanket, eye mask (optional), alarm",
        "instructions": "1. Set an alarm for 20-25 minutes (account for falling asleep).\n2. Lie down in a slightly cool, dark space.\n3. If using a blanket, choose something light.\n4. Close your eyes and let thoughts pass without engaging.\n5. When the alarm rings, sit up slowly, stretch, and drink a glass of water.",
        "benefit": "energy",
        "moon_phase": "any",
    },
    {
        "name": "Hammock Reading",
        "category": "rest",
        "tagline": "Swing between chapters and clouds",
        "description": "Reading a book in a hammock — or any deeply comfortable, slightly swaying spot. The gentle rocking, the fresh air, the story — each one compounds the calm.",
        "duration_min": 60,
        "difficulty": "easy",
        "season": "summer",
        "setting": "outdoor",
        "supplies": "Hammock or comfortable outdoor chair, book, blanket, drink",
        "instructions": "1. Set up your hammock in a shaded spot with a breeze.\n2. Bring a book you're reading for pleasure — not productivity.\n3. Settle in with a blanket and a drink.\n4. Read without a goal — no page targets, no timers.\n5. If you fall asleep, consider that a success.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Candlelit Evening",
        "category": "rest",
        "tagline": "Let firelight soften the edges",
        "description": "Spending an evening by candlelight instead of overhead lights. The soft flicker changes everything — the room, the mood, the pace of the evening. Ancient light for modern tiredness.",
        "duration_min": 120,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Candles (several), matches, cozy blanket",
        "instructions": "1. After sunset, turn off all overhead lights.\n2. Light candles in your main living space — at least three for good light.\n3. Do your usual evening activities by candlelight: cook, read, talk.\n4. Notice how the room feels different. Notice how you feel different.\n5. Blow out the candles when you head to bed. Watch the last wisp of smoke.",
        "benefit": "stress",
        "moon_phase": "full",
    },
    {
        "name": "Screen-Free Morning",
        "category": "rest",
        "tagline": "Let the day begin with you, not a screen",
        "description": "Keeping all screens off for the first hour after waking. No email, no news, no social media. Just you, the morning, and whatever you choose to do with your first waking hour.",
        "duration_min": 60,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Analog alarm clock, book, journal, coffee or tea supplies",
        "instructions": "1. The night before, charge your phone in another room.\n2. Wake with an analog alarm or sunrise alarm clock.\n3. Make coffee or tea without checking any device.\n4. Spend the first hour reading, stretching, journaling, or just sitting.\n5. Notice how differently the day begins when you choose its first input.",
        "benefit": "focus",
        "moon_phase": "new",
    },
    {
        "name": "Restorative Yoga (Legs Up the Wall)",
        "category": "rest",
        "tagline": "Do less. Way, way less.",
        "description": "A single restorative yoga pose — viparita karani — that reverses blood flow, calms the nervous system, and asks absolutely nothing of you except showing up and lying down.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Wall space, yoga mat or blanket, pillow (optional)",
        "instructions": "1. Sit sideways next to a wall, then swing your legs up as you lie back.\n2. Scoot your hips as close to the wall as comfortable.\n3. Rest your arms at your sides, palms up.\n4. Close your eyes and breathe naturally.\n5. Stay for 10-15 minutes. To come out, bend your knees and roll to one side.",
        "benefit": "sleep",
        "moon_phase": "full",
    },
    {
        "name": "Cozy Den Building",
        "category": "rest",
        "tagline": "Build yourself a nest and climb in",
        "description": "Creating a cozy corner or blanket fort for reading, resting, or just being. Pillows, blankets, fairy lights. Childlike? Yes. Necessary? Also yes.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Blankets, pillows, fairy lights (optional), books, snacks",
        "instructions": "1. Choose a corner, couch, or space that feels enclosed and safe.\n2. Layer blankets and pillows to create a soft nest.\n3. Add fairy lights or a lamp for warm, low light.\n4. Bring in a book, journal, or nothing at all.\n5. Climb in and stay as long as you want. No one needs to know.",
        "benefit": "joy",
        "moon_phase": "new",
    },
]


def seed(db_path=None):
    """Seed the database with curated self-care activities."""
    conn = db.init_db(db_path)

    count = 0
    for entry in ACTIVITIES:
        cols = []
        placeholders = []
        values = []
        for key in (
            "name", "category", "description", "tagline", "duration_min",
            "difficulty", "season", "setting", "supplies", "instructions",
            "benefit", "moon_phase",
        ):
            if key in entry:
                cols.append(key)
                placeholders.append("?")
                values.append(entry[key])

        conn.execute(
            f"INSERT OR IGNORE INTO activities ({', '.join(cols)}) VALUES ({', '.join(placeholders)})",
            values,
        )
        count += 1

    conn.commit()
    conn.close()
    print(f"Seeded {count} activities")


if __name__ == "__main__":
    db_path = os.path.join(os.path.dirname(__file__), "self_care.db")
    if os.path.exists(db_path):
        os.remove(db_path)
    seed(db_path)
