"""Seed data for the Only Good Things self-care activity catalog."""

import os

import db

ACTIVITIES = [
    # ── Body (8) ──
    {
        "name": "Morning Stretch Ritual",
        "category": "body",
        "tagline": "Greet the day with your whole body",
        "description": "A gentle 15-minute sequence of stretches designed to wake up your muscles and joints. Move slowly, breathe deeply, and let your body unfold at its own pace.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Yoga mat or soft rug, comfortable clothes",
        "instructions": "1. Stand tall and reach your arms overhead, stretching side to side.\n2. Fold forward gently, letting your head hang heavy.\n3. Come to hands and knees for cat-cow stretches, 5 rounds.\n4. Sit cross-legged and twist gently to each side.\n5. Lie on your back and hug your knees to your chest.",
        "benefit": "energy",
        "moon_phase": "any",
    },
    {
        "name": "Dry Brushing",
        "category": "body",
        "tagline": "Sweep away what no longer serves you",
        "description": "An ancient practice of brushing dry skin with a natural bristle brush to boost circulation and slough off dead skin. A small act that makes your whole body hum.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Natural bristle dry brush",
        "instructions": "1. Start at your feet with long, sweeping strokes toward your heart.\n2. Move up your legs, using firm but gentle pressure.\n3. Brush your arms from fingertips toward shoulders.\n4. Use gentle circular motions on your stomach.\n5. Follow with a warm shower and moisturizer.",
        "benefit": "energy",
        "moon_phase": "waning",
    },
    {
        "name": "Warm Bath Soak",
        "category": "body",
        "tagline": "Dissolve the day in warm water",
        "description": "A slow, intentional bath with salts or oils. Light a candle, put your phone away, and let the warm water hold you. This is not about getting clean — it's about getting quiet.",
        "duration_min": 45,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Epsom salt or bath oil, candle, towel",
        "instructions": "1. Run a warm bath and add a generous handful of Epsom salt or a few drops of essential oil.\n2. Light a candle and dim the overhead lights.\n3. Set your phone in another room.\n4. Soak for at least 20 minutes, breathing deeply.\n5. Pat dry gently and apply body oil while skin is still damp.",
        "benefit": "stress",
        "moon_phase": "full",
    },
    {
        "name": "Face Massage with Oil",
        "category": "body",
        "tagline": "Tend to the face you show the world",
        "description": "A nurturing facial massage using a natural oil like jojoba or rosehip. Releases tension held in the jaw, brow, and temples — places where we store more than we realize.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Facial oil (jojoba, rosehip, or argan), clean hands",
        "instructions": "1. Warm a few drops of oil between your palms.\n2. Press palms gently against your face, holding for a breath.\n3. Use fingertips to make small circles along the jawline.\n4. Smooth across the forehead from center to temples.\n5. Finish with gentle pressure on the temples, holding for five breaths.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Scalp Massage",
        "category": "body",
        "tagline": "Unwind from the top down",
        "description": "A deeply relaxing self-massage focused on the scalp, where we hold surprising amounts of tension. Use your fingertips or a simple scalp massager for an instant calm.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Scalp massager (optional), hair oil (optional)",
        "instructions": "1. Sit comfortably and close your eyes.\n2. Place all ten fingertips on your scalp.\n3. Make small, firm circles, starting at the hairline.\n4. Work slowly toward the crown and down to the nape.\n5. Spend extra time on any spots that feel tender or tight.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Walking Meditation",
        "category": "body",
        "tagline": "Each step is its own arrival",
        "description": "A practice of walking slowly and deliberately, paying attention to the sensation of each footfall. Not about getting somewhere — about being fully here with each step.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "either",
        "supplies": "Comfortable shoes, a quiet path",
        "instructions": "1. Stand still for a moment, feeling your weight on the earth.\n2. Begin walking very slowly, noticing the lift, swing, and placement of each foot.\n3. Let your arms hang naturally at your sides.\n4. When your mind wanders, gently bring attention back to the soles of your feet.\n5. Walk for 10-20 minutes, then stand still again before resuming normal pace.",
        "benefit": "focus",
        "moon_phase": "any",
    },
    {
        "name": "Gentle Yoga Flow",
        "category": "body",
        "tagline": "Move like water, not like a machine",
        "description": "A slow, breath-linked yoga sequence focused on ease rather than achievement. No perfect poses — just your body, your breath, and the space between them.",
        "duration_min": 30,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Yoga mat, blocks (optional), blanket",
        "instructions": "1. Begin in child's pose, breathing deeply for one minute.\n2. Move through 5 slow sun salutations, pausing in each shape.\n3. Hold warrior II on each side for 5 breaths.\n4. Flow through pigeon pose on each side, staying for 10 breaths.\n5. End in savasana for at least 3 minutes.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Cold Plunge Breathing",
        "category": "body",
        "tagline": "Meet the cold and find your calm",
        "description": "A breathwork practice paired with cold water exposure — even just turning the shower cold for the final 30 seconds. Builds resilience and floods the body with aliveness.",
        "duration_min": 10,
        "difficulty": "involved",
        "season": "all",
        "setting": "indoor",
        "supplies": "Shower or cold water access, towel",
        "instructions": "1. Take 30 deep breaths — in through the nose, out through the mouth.\n2. Hold your breath after the last exhale for as long as comfortable.\n3. Take one deep recovery breath and hold for 15 seconds.\n4. Repeat the breathing cycle two more times.\n5. Turn the shower to cold for 30-60 seconds, breathing steadily.",
        "benefit": "energy",
        "moon_phase": "new",
    },

    # ── Body (continued) ──
    {
        "name": "Foam Rolling",
        "category": "body",
        "tagline": "Iron out the knots the day tied",
        "description": "Using a foam roller to release tension in tight muscles. Slow, steady pressure on sore spots melts away stiffness and restores range of motion.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Foam roller, yoga mat",
        "instructions": "1. Start with your calves, rolling slowly from ankle to knee.\n2. Move to your thighs, spending extra time on tight spots.\n3. Roll your upper back, keeping your core engaged.\n4. Pause on any tender point for 20-30 seconds.\n5. Finish by lying flat on the roller along your spine, arms wide.",
        "benefit": "stress",
        "moon_phase": "waning",
    },
    {
        "name": "Hand & Foot Soak",
        "category": "body",
        "tagline": "Warmth where you need it most",
        "description": "A simple soak for tired hands or feet in warm water with Epsom salt and a few drops of essential oil. The extremities carry so much — give them a moment of care.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Basin, warm water, Epsom salt, essential oil, towel",
        "instructions": "1. Fill a basin with comfortably hot water.\n2. Add a handful of Epsom salt and 2-3 drops of lavender or peppermint oil.\n3. Submerge your hands or feet and let them rest.\n4. Close your eyes and breathe deeply for 15 minutes.\n5. Pat dry and apply a rich moisturizer.",
        "benefit": "stress",
        "moon_phase": "full",
    },
    {
        "name": "Dance Break",
        "category": "body",
        "tagline": "Move without a mirror or a reason",
        "description": "Put on one song and dance like nobody's watching — because nobody is. Shake, sway, stomp, spin. Three minutes of unself-conscious movement resets everything.",
        "duration_min": 5,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Music, a little space",
        "instructions": "1. Pick a song that makes your body want to move.\n2. Close the curtains if it helps.\n3. Press play and let your body respond — no choreography.\n4. Move bigger than you think you should.\n5. When the song ends, stand still and feel the buzz.",
        "benefit": "energy",
        "moon_phase": "any",
    },
    {
        "name": "Progressive Muscle Relaxation",
        "category": "body",
        "tagline": "Tense to release, hold to let go",
        "description": "A technique of deliberately tensing each muscle group for five seconds, then releasing. The contrast between tension and relaxation teaches the body what letting go really feels like.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Comfortable surface, quiet space",
        "instructions": "1. Lie down and take three deep breaths.\n2. Start with your feet — curl your toes tightly for 5 seconds, then release.\n3. Move up: calves, thighs, stomach, fists, arms, shoulders, face.\n4. Tense each group for 5 seconds, then let go completely.\n5. After the last group, lie still for 2 minutes feeling the total relaxation.",
        "benefit": "sleep",
        "moon_phase": "full",
    },
    {
        "name": "Barefoot Grounding",
        "category": "body",
        "tagline": "Remember you belong to the earth",
        "description": "Walking barefoot on grass, sand, or soil — also called earthing. Direct contact between your feet and the ground has a way of resetting something deep and wordless.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "summer",
        "setting": "outdoor",
        "supplies": "A patch of grass, sand, or soil",
        "instructions": "1. Find a clean patch of natural ground — grass, earth, or sand.\n2. Remove your shoes and socks.\n3. Stand still for a moment, feeling the temperature and texture.\n4. Walk slowly, noticing each sensation under your feet.\n5. Stand still again at the end. Feel the connection.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Self-Massage with Tennis Ball",
        "category": "body",
        "tagline": "Find the knot and have a conversation with it",
        "description": "Using a tennis ball against a wall or floor to release deep tension in your back, shoulders, and feet. Precise, focused pressure that goes where hands can't reach.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Tennis ball or lacrosse ball",
        "instructions": "1. Place the ball between your back and a wall.\n2. Lean into it and roll slowly, searching for tight spots.\n3. When you find one, hold steady pressure for 20-30 seconds.\n4. Move to your shoulders, glutes, and the arches of your feet.\n5. Breathe deeply into each spot — tension releases on the exhale.",
        "benefit": "stress",
        "moon_phase": "waning",
    },
    {
        "name": "Neck & Shoulder Release",
        "category": "body",
        "tagline": "Put down what you've been carrying",
        "description": "A targeted sequence for the neck and shoulders — where most of us hold stress without realizing it. Five minutes of gentle stretching can undo hours of desk posture.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "either",
        "supplies": "None",
        "instructions": "1. Drop your chin to your chest and hold for 5 breaths.\n2. Tilt your right ear to your right shoulder, hold for 5 breaths. Switch sides.\n3. Interlace fingers behind your back and lift your arms gently.\n4. Roll your shoulders backward 10 times, then forward 10 times.\n5. Shake out your arms and hands. Let everything be loose.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Abhyanga (Self-Oil Massage)",
        "category": "body",
        "tagline": "Anoint yourself with warmth and attention",
        "description": "An Ayurvedic practice of massaging warm oil into the entire body before bathing. A profound act of self-love that nourishes the skin and calms the nervous system.",
        "duration_min": 30,
        "difficulty": "moderate",
        "season": "fall",
        "setting": "indoor",
        "supplies": "Sesame or coconut oil, towel, warm bathroom",
        "instructions": "1. Warm the oil by placing the bottle in a bowl of hot water.\n2. Sit on an old towel and begin at your scalp with circular motions.\n3. Use long strokes on your limbs, circles on your joints.\n4. Massage your abdomen in clockwise circles.\n5. Let the oil soak in for 10-15 minutes, then shower with warm water.",
        "benefit": "stress",
        "moon_phase": "waning",
    },
    {
        "name": "Morning Sun Exposure",
        "category": "body",
        "tagline": "Let first light set your inner clock",
        "description": "Getting 10 minutes of natural sunlight within the first hour of waking. It resets your circadian rhythm, boosts serotonin, and sets the stage for better sleep that night.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "None — just step outside",
        "instructions": "1. Within 30-60 minutes of waking, go outside.\n2. Face the general direction of the sun (never stare directly).\n3. Let the light reach your eyes — no sunglasses.\n4. Walk, stretch, or simply stand and breathe.\n5. Stay for at least 10 minutes. Notice how alert you begin to feel.",
        "benefit": "energy",
        "moon_phase": "any",
    },

    # ── Mind (8) ──
    {
        "name": "Journaling Prompts",
        "category": "mind",
        "tagline": "Let the pen find what the mind hides",
        "description": "Guided freewriting using a single prompt to unlock thoughts you didn't know you were carrying. Not about beautiful writing — about honest writing.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Notebook, pen",
        "instructions": "1. Choose a prompt: 'What am I avoiding?' or 'What would I do if no one was watching?'\n2. Set a timer for 15 minutes.\n3. Write without stopping — don't edit, don't reread.\n4. If you get stuck, write 'I'm stuck' until something else comes.\n5. When the timer ends, close the notebook without rereading.",
        "benefit": "focus",
        "moon_phase": "new",
    },
    {
        "name": "Guided Meditation",
        "category": "mind",
        "tagline": "Borrow someone else's calm for a while",
        "description": "A led meditation practice using an app or recording. Let someone else do the thinking while you simply follow along. Perfect for days when your own mind is too loud.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Phone or speaker, meditation app or recording, cushion",
        "instructions": "1. Find a quiet space and sit or lie down comfortably.\n2. Choose a guided meditation (body scan, loving-kindness, or breath focus).\n3. Press play and close your eyes.\n4. Follow the guide's instructions without judging your experience.\n5. When it ends, sit quietly for one more minute before moving.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Box Breathing",
        "category": "mind",
        "tagline": "Four sides of a single breath",
        "description": "A structured breathing technique used by Navy SEALs and monks alike. Inhale, hold, exhale, hold — each for the same count. Remarkably effective at calming the nervous system.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "either",
        "supplies": "None — just yourself",
        "instructions": "1. Sit upright with your feet flat on the floor.\n2. Inhale slowly through your nose for 4 counts.\n3. Hold your breath for 4 counts.\n4. Exhale slowly through your mouth for 4 counts.\n5. Hold empty for 4 counts. Repeat for 5-10 minutes.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Digital Detox Hour",
        "category": "mind",
        "tagline": "An hour without the glow",
        "description": "One full hour with all screens turned off. Not hidden — turned off. Rediscover what your hands and eyes do when they're not scrolling. It's stranger and lovelier than you'd expect.",
        "duration_min": 60,
        "difficulty": "moderate",
        "season": "all",
        "setting": "either",
        "supplies": "A book, sketchpad, or nothing at all",
        "instructions": "1. Set a timer on a non-screen device (kitchen timer, watch).\n2. Power off or place all screens in a drawer.\n3. Resist the urge to check — notice the impulse and let it pass.\n4. Do whatever calls to you: read, draw, sit, walk, cook.\n5. When the hour ends, notice how you feel before turning anything back on.",
        "benefit": "focus",
        "moon_phase": "full",
    },
    {
        "name": "Gratitude List",
        "category": "mind",
        "tagline": "Count what counts",
        "description": "Writing down five specific things you're grateful for today. Not big, abstract things — small, real ones. The warmth of your coffee. A text from a friend. The way light hit the wall.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Notebook, pen",
        "instructions": "1. Sit quietly and close your eyes for a moment.\n2. Think about the last 24 hours.\n3. Write down 5 specific things you're grateful for — be detailed.\n4. For each one, write why it matters to you.\n5. Read the list back to yourself slowly.",
        "benefit": "joy",
        "moon_phase": "full",
    },
    {
        "name": "Brain Dump Writing",
        "category": "mind",
        "tagline": "Empty the jar so it can fill again",
        "description": "Pouring every thought, worry, task, and half-idea out of your head and onto paper. Not organized, not prioritized — just out. The relief is immediate and real.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Large blank paper or notebook, pen",
        "instructions": "1. Get a large piece of paper — bigger than usual.\n2. Set a timer for 10 minutes.\n3. Write down everything in your head: tasks, worries, ideas, names, feelings.\n4. Don't organize — just dump. Use arrows, circles, margins.\n5. When done, circle the 3 most important items. Let the rest wait.",
        "benefit": "focus",
        "moon_phase": "waning",
    },
    {
        "name": "Mindful Tea Ceremony",
        "category": "mind",
        "tagline": "One cup, made with your whole attention",
        "description": "Making and drinking a single cup of tea with complete presence. Hear the water boil, watch the color bloom, feel the warmth in your hands. A tiny ceremony that resets the day.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Loose leaf tea or tea bag, kettle, favorite cup",
        "instructions": "1. Fill the kettle and listen to the water begin to heat.\n2. Choose your tea with intention — what does today call for?\n3. Pour the water slowly and watch the color change.\n4. Hold the cup with both hands and breathe in the steam.\n5. Drink slowly, tasting each sip as if it were the first.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Body Scan Meditation",
        "category": "mind",
        "tagline": "Visit every room in the house of your body",
        "description": "A systematic meditation that moves attention slowly from head to toes (or toes to head), noticing sensations without trying to change them. Deeply grounding and quietly revelatory.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Comfortable surface to lie on, blanket",
        "instructions": "1. Lie down on your back with arms at your sides.\n2. Close your eyes and take five deep breaths.\n3. Bring attention to the top of your head, then slowly move down.\n4. Notice each area without judgment: forehead, jaw, neck, shoulders, and so on.\n5. When you reach your toes, take three deep breaths and slowly open your eyes.",
        "benefit": "sleep",
        "moon_phase": "full",
    },

    # ── Mind (continued) ──
    {
        "name": "Loving-Kindness Meditation",
        "category": "mind",
        "tagline": "Send warmth to yourself and then outward",
        "description": "A meditation where you silently repeat phrases of goodwill — first to yourself, then to loved ones, then to strangers, then to all beings. Surprisingly powerful in its simplicity.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Cushion or chair, quiet space",
        "instructions": "1. Sit comfortably and close your eyes.\n2. Silently repeat: 'May I be happy. May I be healthy. May I be safe.'\n3. Bring to mind someone you love — repeat the phrases for them.\n4. Think of a neutral person (a stranger) — repeat for them.\n5. Expand to all beings everywhere. Sit in that feeling for a moment.",
        "benefit": "connection",
        "moon_phase": "full",
    },
    {
        "name": "Worry Time Scheduling",
        "category": "mind",
        "tagline": "Give worry a chair, but only for ten minutes",
        "description": "A cognitive behavioral technique where you designate a specific 10-minute window for worrying — and postpone all anxious thoughts to that time. Surprisingly, most worries don't show up.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Notebook, pen, timer",
        "instructions": "1. Choose a daily 10-minute worry window (e.g., 5:00 PM).\n2. During the day, when a worry arises, write it on a list and postpone it.\n3. At your designated time, sit with your list.\n4. Spend up to 10 minutes actively worrying about each item.\n5. When the timer ends, close the notebook. Most worries will feel smaller.",
        "benefit": "stress",
        "moon_phase": "waning",
    },
    {
        "name": "Five Senses Check-In",
        "category": "mind",
        "tagline": "Arrive in the present through your senses",
        "description": "A quick grounding exercise: name five things you see, four you hear, three you feel, two you smell, one you taste. Pulls you out of spiraling thoughts and back into the room.",
        "duration_min": 5,
        "difficulty": "easy",
        "season": "all",
        "setting": "either",
        "supplies": "None",
        "instructions": "1. Pause wherever you are and take one deep breath.\n2. Name 5 things you can see — be specific.\n3. Name 4 things you can hear, including quiet sounds.\n4. Name 3 things you can physically feel (clothes, air, chair).\n5. Name 2 things you can smell and 1 you can taste. You're here now.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Intention Setting",
        "category": "mind",
        "tagline": "Choose one word to carry through the day",
        "description": "Choosing a single word or short phrase to guide your day — not a goal, not a to-do, but a quality you want to embody. Patience. Openness. Ease. Let it color everything.",
        "duration_min": 5,
        "difficulty": "easy",
        "season": "all",
        "setting": "either",
        "supplies": "Notebook (optional)",
        "instructions": "1. Sit quietly for a moment before the day begins.\n2. Ask yourself: what quality do I want to bring to today?\n3. Let a word or phrase arise — don't force it.\n4. Write it down or hold it in your mind.\n5. Return to it throughout the day, especially in difficult moments.",
        "benefit": "focus",
        "moon_phase": "new",
    },
    {
        "name": "Evening Reflection",
        "category": "mind",
        "tagline": "Close the day with a gentle accounting",
        "description": "A brief nightly practice of reviewing the day without judgment. What went well? What was hard? What surprised you? Not a performance review — a quiet noticing.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Notebook, pen",
        "instructions": "1. At the end of the day, sit quietly with your notebook.\n2. Write one thing that went well today.\n3. Write one thing that was difficult.\n4. Write one thing that surprised you.\n5. Close with one thing you're looking forward to tomorrow.",
        "benefit": "sleep",
        "moon_phase": "any",
    },
    {
        "name": "Mantra Repetition",
        "category": "mind",
        "tagline": "One phrase, repeated until it becomes a feeling",
        "description": "Sitting quietly and repeating a meaningful word or phrase — aloud or silently. The repetition creates a rhythm that calms the mind and anchors attention.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Mala beads (optional), quiet space",
        "instructions": "1. Choose a mantra: 'I am enough,' 'Peace,' 'Let go,' or anything that resonates.\n2. Sit comfortably and close your eyes.\n3. Repeat the mantra slowly, either aloud or silently.\n4. If using mala beads, move one bead per repetition.\n5. Continue for 10 minutes. Let the words dissolve into feeling.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Savoring Practice",
        "category": "mind",
        "tagline": "Stretch a good moment until it fills you",
        "description": "Deliberately pausing during a pleasant experience to fully absorb it. A bite of food, a warm breeze, a laugh. Most good moments pass unnoticed — this practice catches them.",
        "duration_min": 5,
        "difficulty": "easy",
        "season": "all",
        "setting": "either",
        "supplies": "None — just awareness",
        "instructions": "1. During a pleasant moment, pause.\n2. Name what's good about it — be specific.\n3. Notice it with all your senses.\n4. Let the feeling expand in your body.\n5. Tell yourself: 'This is happening. I'm here for it.'",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Letter to Future Self",
        "category": "mind",
        "tagline": "Write across time to someone you trust",
        "description": "Writing a letter to yourself six months or a year from now. What do you hope for? What do you want to remember about this moment? A time capsule in ink.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Nice paper, pen, envelope",
        "instructions": "1. Date the letter for 6 months or 1 year from today.\n2. Describe your life right now — what fills your days, what you're feeling.\n3. Write what you hope will be different and what you hope stays the same.\n4. Include a piece of advice from present-you.\n5. Seal it in an envelope, write the date to open, and put it somewhere safe.",
        "benefit": "focus",
        "moon_phase": "new",
    },
    {
        "name": "Silence Sitting",
        "category": "mind",
        "tagline": "Do nothing, completely",
        "description": "Sitting in total silence with no agenda — no meditation technique, no mantra, no guidance. Just you and the quiet. Harder and more rewarding than almost anything on this list.",
        "duration_min": 15,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Timer, quiet room",
        "instructions": "1. Find the quietest room available.\n2. Set a timer for 15 minutes.\n3. Sit in a comfortable position and do nothing.\n4. No technique — just sit. Let thoughts come and go.\n5. When the timer sounds, take one deep breath before standing.",
        "benefit": "stress",
        "moon_phase": "new",
    },

    # ── Creative (8) ──
    {
        "name": "Watercolor Painting",
        "category": "creative",
        "tagline": "Let the water lead",
        "description": "Loose, intuitive watercolor painting — not about making something perfect, but about watching color move through water. The medium teaches you to let go of control.",
        "duration_min": 45,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Watercolor set, brushes, watercolor paper, water cup, rag",
        "instructions": "1. Wet your paper with clean water using a large brush.\n2. Choose 2-3 colors that feel right today.\n3. Touch the wet paper with loaded brush and watch the color bloom.\n4. Add more color or water, letting shapes emerge on their own.\n5. Let it dry completely. Name it something unexpected.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Collage Making",
        "category": "creative",
        "tagline": "Rearrange the world on paper",
        "description": "Cutting and arranging images from magazines, old books, or printed photos into something new. A tactile, low-pressure creative practice that lets your subconscious do the composing.",
        "duration_min": 60,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Old magazines or printed images, scissors, glue stick, cardstock",
        "instructions": "1. Gather a stack of magazines or printed images.\n2. Flip through and tear out anything that catches your eye — don't overthink it.\n3. Cut out shapes, words, textures that appeal to you.\n4. Arrange pieces on cardstock, moving them around until something clicks.\n5. Glue down and let it be what it is.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Poetry Writing",
        "category": "creative",
        "tagline": "Say the unsayable in fewer words",
        "description": "Writing a short poem — even just three lines. Poetry isn't about rhyming or rules; it's about paying close enough attention that language becomes a window.",
        "duration_min": 30,
        "difficulty": "moderate",
        "season": "all",
        "setting": "either",
        "supplies": "Notebook, pen",
        "instructions": "1. Look around you and choose one small thing to describe.\n2. Write three specific details about it — what does it look like, sound like, feel like?\n3. Arrange those details into lines, cutting unnecessary words.\n4. Read it aloud — does it sound like you?\n5. Give it a title that surprises you.",
        "benefit": "focus",
        "moon_phase": "new",
    },
    {
        "name": "Playlist Curation",
        "category": "creative",
        "tagline": "Score the soundtrack to a feeling",
        "description": "Building a playlist with intention — not shuffling, but choosing each song for a mood, a memory, or a moment. A creative act disguised as something ordinary.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Music streaming app, headphones",
        "instructions": "1. Choose a theme: a season, a feeling, a person, a time of day.\n2. Pick an opening track that sets the tone.\n3. Build the arc — let each song flow into the next.\n4. Aim for 10-15 songs, about 45 minutes.\n5. Name the playlist something only you'd understand.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Flower Arranging",
        "category": "creative",
        "tagline": "Bring the outside in, stem by stem",
        "description": "Arranging flowers — from a market bouquet or even roadside wildflowers — into a vase with intention. A practice in color, balance, and impermanence.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "spring",
        "setting": "indoor",
        "supplies": "Flowers (fresh or foraged), vase, scissors or garden shears",
        "instructions": "1. Gather your flowers and trim stems at an angle under water.\n2. Remove any leaves that will sit below the waterline.\n3. Start with your largest stems as the structure.\n4. Fill in with smaller blooms and greenery, turning the vase as you go.\n5. Place somewhere you'll see it often. Notice it change over the days.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Hand Lettering Practice",
        "category": "creative",
        "tagline": "Slow down to the speed of ink",
        "description": "Practicing beautiful letterforms with a pen or brush marker. Not about perfection — about the meditative rhythm of forming each letter with care and attention.",
        "duration_min": 30,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Brush pen or felt-tip marker, practice paper or dot grid notebook",
        "instructions": "1. Choose a word or short phrase that means something to you.\n2. Practice the basic strokes: thin upstrokes, thick downstrokes.\n3. Write the word slowly, focusing on each letter.\n4. Try it three different ways — larger, smaller, different spacing.\n5. Choose your favorite version and trace it with intention.",
        "benefit": "focus",
        "moon_phase": "any",
    },
    {
        "name": "Photography Walk",
        "category": "creative",
        "tagline": "See your world as if for the first time",
        "description": "A walk with the sole purpose of taking photographs — with your phone or a camera. Constraints help: only shoot shadows, or only red things, or only textures. Seeing changes when you look with purpose.",
        "duration_min": 45,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "Camera or phone, comfortable shoes",
        "instructions": "1. Choose a constraint: one color, one shape, or one theme (doors, light, hands).\n2. Walk your neighborhood with fresh eyes.\n3. Take at least 20 photos — don't be precious about them.\n4. Stop when something surprises you and really look before shooting.\n5. Choose 3 favorites and consider why they stand out.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Mending & Visible Repair",
        "category": "creative",
        "tagline": "Honor the tear instead of hiding it",
        "description": "Repairing a garment using visible stitching or patching — inspired by the Japanese philosophy of kintsugi. The mend becomes a feature, not a flaw. A meditation on imperfection.",
        "duration_min": 45,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Garment to mend, embroidery thread, needle, fabric scraps (optional)",
        "instructions": "1. Choose a garment with a tear, hole, or worn spot.\n2. Select thread in a contrasting color — the repair should be seen.\n3. Use a running stitch, sashiko pattern, or simple patch.\n4. Work slowly, enjoying the repetitive motion of the needle.\n5. Wear the mended garment with pride.",
        "benefit": "focus",
        "moon_phase": "waxing",
    },

    # ── Creative (continued) ──
    {
        "name": "Zentangle Drawing",
        "category": "creative",
        "tagline": "Structured doodling for an unstructured mind",
        "description": "Creating small, intricate patterns within defined spaces. Repetitive, focused, and oddly calming. No artistic skill needed — just a pen and the willingness to fill a square.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Fine-tip pen, small squares of paper or a sketchbook",
        "instructions": "1. Draw a 3.5-inch square on your paper.\n2. Draw a loose border line inside the square.\n3. Divide the space into sections with light pencil lines.\n4. Fill each section with a different repeating pattern.\n5. When the square is full, go over pencil lines with pen and erase the pencil.",
        "benefit": "focus",
        "moon_phase": "any",
    },
    {
        "name": "Clay or Playdough Sculpting",
        "category": "creative",
        "tagline": "Think with your hands",
        "description": "Working with clay or even homemade playdough. The tactile sensation of shaping something with your hands engages the brain differently than any screen-based activity.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Air-dry clay or playdough, work surface, simple tools (optional)",
        "instructions": "1. Take a palm-sized piece of clay and warm it in your hands.\n2. Start by rolling, pressing, and pinching without a plan.\n3. Let a shape emerge — a bowl, an animal, an abstract form.\n4. Use simple tools (a fork, a pencil) to add texture.\n5. Set it aside to dry, or squish it flat and start again.",
        "benefit": "stress",
        "moon_phase": "waxing",
    },
    {
        "name": "Nature Journaling",
        "category": "creative",
        "tagline": "Draw what you notice, notice what you draw",
        "description": "Sketching and noting what you observe in nature — a leaf, a cloud formation, the way moss grows on stone. Part art, part science, all attention.",
        "duration_min": 30,
        "difficulty": "moderate",
        "season": "spring",
        "setting": "outdoor",
        "supplies": "Sketchbook, pencil, colored pencils (optional)",
        "instructions": "1. Go to a natural spot and sit quietly for 5 minutes.\n2. Choose one thing to observe closely — a plant, insect, or pattern.\n3. Sketch it, focusing on shapes and proportions.\n4. Add notes: date, location, weather, colors, what surprised you.\n5. Over time, your journal becomes a record of attention.",
        "benefit": "focus",
        "moon_phase": "any",
    },
    {
        "name": "Blackout Poetry",
        "category": "creative",
        "tagline": "Find the poem hiding in the page",
        "description": "Taking a page of printed text and blacking out most of the words, leaving only a few to form a new poem. Destruction as creation. The poem was always there — you just revealed it.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Old book or newspaper page, black marker, pencil",
        "instructions": "1. Choose a page from an old book or newspaper.\n2. Read through and circle words that catch your eye.\n3. Try to connect the circled words into a phrase or poem.\n4. Lightly pencil in which words to keep.\n5. Black out everything else with a marker. Read your poem aloud.",
        "benefit": "joy",
        "moon_phase": "waning",
    },
    {
        "name": "Gratitude Jar",
        "category": "creative",
        "tagline": "Collect your good days in a jar",
        "description": "Writing small moments of joy or gratitude on slips of paper and collecting them in a jar. On hard days, pull a few out and read them. A tangible archive of goodness.",
        "duration_min": 5,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Glass jar, small slips of paper, pen",
        "instructions": "1. Keep a jar and slips of paper somewhere visible.\n2. Each day, write one good thing on a slip.\n3. Fold it and drop it in the jar.\n4. Watch it fill over weeks and months.\n5. On a difficult day, pull out a handful and read them.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Embroidery or Cross-Stitch",
        "category": "creative",
        "tagline": "One stitch, then another, then a garden",
        "description": "A slow, repetitive needlework practice that produces something beautiful over time. The rhythm of the needle is meditative, and the result is uniquely yours.",
        "duration_min": 45,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Embroidery hoop, fabric, needle, embroidery thread, pattern (optional)",
        "instructions": "1. Stretch fabric in an embroidery hoop.\n2. Choose a simple design — a flower, a word, a geometric shape.\n3. Thread your needle and begin with basic stitches (backstitch, satin stitch).\n4. Work slowly, keeping tension even.\n5. Display your finished piece or gift it to someone.",
        "benefit": "focus",
        "moon_phase": "waxing",
    },
    {
        "name": "Vision Board Making",
        "category": "creative",
        "tagline": "Show yourself what you're dreaming toward",
        "description": "Creating a visual collage of images, words, and textures that represent your aspirations and values. Not magical thinking — intentional seeing.",
        "duration_min": 60,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Poster board, magazines, scissors, glue, markers",
        "instructions": "1. Gather magazines, printed images, and materials.\n2. Spend time thinking about what you want more of in your life.\n3. Cut out images, words, and textures that resonate.\n4. Arrange them on poster board — no wrong way to do this.\n5. Hang it where you'll see it daily.",
        "benefit": "joy",
        "moon_phase": "new",
    },
    {
        "name": "Album Listening (Front to Back)",
        "category": "creative",
        "tagline": "Hear a whole story, not just a single",
        "description": "Listening to an entire album from start to finish without skipping — the way the artist intended. A lost art in the age of playlists and shuffle.",
        "duration_min": 45,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Music player, headphones, comfortable spot",
        "instructions": "1. Choose an album you love or one you've been meaning to hear.\n2. Put on headphones and press play from track one.\n3. Close your eyes or do something quiet with your hands.\n4. Listen without skipping — let the album breathe.\n5. When it ends, sit in the silence for a moment before moving on.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Pressed Flower Art",
        "category": "creative",
        "tagline": "Flatten time between the pages",
        "description": "Pressing flowers and leaves between book pages, then arranging them into art. A practice that spans days — the pressing, the waiting, the composing. Patience as medium.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "spring",
        "setting": "either",
        "supplies": "Fresh flowers or leaves, heavy books, parchment paper, frame (optional)",
        "instructions": "1. Gather flowers and leaves — choose flat varieties for best results.\n2. Place them between sheets of parchment paper inside a heavy book.\n3. Stack more books on top and wait 1-2 weeks.\n4. Carefully remove the pressed flowers.\n5. Arrange on paper or cardstock and frame, or use as bookmarks.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },

    # ── Nature (7) ──
    {
        "name": "Forest Bathing",
        "category": "nature",
        "tagline": "Let the trees hold you for a while",
        "description": "Shinrin-yoku — the Japanese practice of immersing yourself in the forest atmosphere. Not hiking, not exercising — just being among trees. Research shows it lowers cortisol, blood pressure, and heart rate.",
        "duration_min": 60,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "Comfortable shoes, layers for weather",
        "instructions": "1. Find a wooded area — even a large park with mature trees.\n2. Leave your phone in your pocket or bag.\n3. Walk very slowly, with no destination.\n4. Engage all senses: touch bark, smell earth, listen for birds.\n5. Find a spot to sit for 10 minutes, just breathing and being.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Cloud Watching",
        "category": "nature",
        "tagline": "The sky's slow cinema",
        "description": "Lying on your back and watching clouds — genuinely, deliberately, like it matters. Because it does. There is no faster way to remember how large the world is and how small your worries are.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "summer",
        "setting": "outdoor",
        "supplies": "Blanket, open sky",
        "instructions": "1. Find an open spot with a wide view of the sky.\n2. Spread a blanket and lie on your back.\n3. Let your eyes soften and take in the whole sky.\n4. Watch individual clouds — notice their shapes, speed, and layers.\n5. Stay for at least 15 minutes. Let yourself do absolutely nothing else.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Herb Garden Tending",
        "category": "nature",
        "tagline": "Grow something you can taste",
        "description": "Caring for a small herb garden — even just a few pots on a windowsill. Watering, pruning, harvesting. The simplest form of nurturing something alive.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "spring",
        "setting": "either",
        "supplies": "Herb pots (basil, mint, rosemary), watering can, small scissors",
        "instructions": "1. Check soil moisture — water if the top inch is dry.\n2. Pinch off any dead or yellowing leaves.\n3. Harvest a few leaves for cooking or tea.\n4. Turn pots so all sides get sunlight.\n5. Talk to them if you want. Plants don't judge.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Sunrise or Sunset Watching",
        "category": "nature",
        "tagline": "Witness the world turning",
        "description": "Sitting still to watch the sun rise or set — the full show, from first color to last. No photos required. Just your eyes, the horizon, and the ancient slow spectacle of light.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "Warm layers, a good vantage point, a warm drink (optional)",
        "instructions": "1. Check the time for sunrise or sunset in your area.\n2. Arrive 15 minutes early to settle in.\n3. Find a comfortable spot with a clear view of the horizon.\n4. Put your phone away and just watch.\n5. Stay until the color has fully faded. Notice the afterglow.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Night Sky Stargazing",
        "category": "nature",
        "tagline": "Remember you are made of the same stuff",
        "description": "Spending time under the night sky, looking up. Learn one constellation, or learn none — just look. The dark and the distance have a way of putting things in perspective.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "winter",
        "setting": "outdoor",
        "supplies": "Blanket or chair, warm layers, star chart app (optional)",
        "instructions": "1. Find the darkest spot you can — away from streetlights.\n2. Give your eyes 10 minutes to adjust to the dark.\n3. Look for familiar patterns — the Big Dipper, Orion's Belt.\n4. Try to spot a planet (they don't twinkle like stars).\n5. Lie back and let the scale of it sink in.",
        "benefit": "stress",
        "moon_phase": "new",
    },
    {
        "name": "Foraging Walk",
        "category": "nature",
        "tagline": "The earth sets a table if you know where to look",
        "description": "A walk with the intention of identifying and gathering wild edibles — herbs, berries, mushrooms. Always with proper identification and respect for the ecosystem.",
        "duration_min": 60,
        "difficulty": "involved",
        "season": "fall",
        "setting": "outdoor",
        "supplies": "Field guide or foraging app, basket or bag, gloves",
        "instructions": "1. Research what's in season in your area before heading out.\n2. Bring a reliable field guide — never eat anything you're unsure about.\n3. Walk slowly, scanning the ground and lower branches.\n4. Harvest only what you'll use, and never take more than a third of any patch.\n5. At home, clean and prepare your finds with gratitude.",
        "benefit": "joy",
        "moon_phase": "full",
    },
    {
        "name": "Bird Watching",
        "category": "nature",
        "tagline": "Learn the names of your neighbors",
        "description": "Sitting quietly and watching birds — in your yard, a park, or anywhere outdoors. Once you start noticing, the world fills with wings. A practice in patience and attention.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "spring",
        "setting": "outdoor",
        "supplies": "Binoculars (optional), bird identification app or field guide, notebook",
        "instructions": "1. Find a quiet spot outdoors and sit still.\n2. Listen first — most birds are heard before they're seen.\n3. When you spot one, notice its size, color, and movement patterns.\n4. Try to identify it using your guide or app.\n5. Keep a simple list of what you see — it becomes a journal over time.",
        "benefit": "focus",
        "moon_phase": "any",
    },

    # ── Nature (continued) ──
    {
        "name": "Rain Listening",
        "category": "nature",
        "tagline": "The sky is playing your favorite album",
        "description": "Sitting near an open window or under a covered porch while it rains, just listening. Rain is the original white noise — rhythmic, unpredictable, and deeply soothing.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "spring",
        "setting": "either",
        "supplies": "An open window or covered porch, blanket, warm drink",
        "instructions": "1. When it starts raining, find a spot near an open window or under cover outside.\n2. Settle in with a blanket and something warm to drink.\n3. Close your eyes and listen to the layers — roof, leaves, pavement, gutters.\n4. Notice the rhythm change as the rain intensifies or softens.\n5. Stay until the rain stops or until you feel full.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Leaf Collecting",
        "category": "nature",
        "tagline": "Hold autumn in your hands",
        "description": "Walking to gather fallen leaves in their most vivid colors. Press them, arrange them, or just carry them home. A practice in noticing color, shape, and the beauty of letting go.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "fall",
        "setting": "outdoor",
        "supplies": "A bag or book to carry leaves, comfortable shoes",
        "instructions": "1. Take a walk where trees are abundant.\n2. Look for leaves with interesting colors, shapes, or patterns.\n3. Pick up only fallen leaves — they've already let go.\n4. Carry them carefully in a book or bag.\n5. At home, press them in a book or arrange them on a windowsill.",
        "benefit": "joy",
        "moon_phase": "waning",
    },
    {
        "name": "Outdoor Sitting Spot",
        "category": "nature",
        "tagline": "Claim a square of earth and return to it",
        "description": "Choosing one spot outdoors and returning to it regularly — the same bench, the same tree, the same patch of grass. Over time, you notice things that only stillness reveals.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "None — just yourself and your spot",
        "instructions": "1. Choose a spot outdoors that feels right — a bench, a rock, a tree.\n2. Visit it regularly, at different times and in different weather.\n3. Sit quietly for at least 15 minutes each visit.\n4. Notice what changes and what stays the same.\n5. Over weeks, you'll see things that casual visitors never notice.",
        "benefit": "focus",
        "moon_phase": "any",
    },
    {
        "name": "Moon Watching",
        "category": "nature",
        "tagline": "Track the oldest clock in the sky",
        "description": "Stepping outside to observe the moon — its phase, its position, its light. A practice of noticing the largest rhythms we live inside of without usually seeing.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "Clear sky, moon phase calendar (optional)",
        "instructions": "1. Step outside after dark and find the moon.\n2. Notice its phase — crescent, quarter, gibbous, full.\n3. Observe its color and position in the sky.\n4. Stand or sit with it for a few minutes.\n5. Check a moon calendar to learn what phase you're in.",
        "benefit": "stress",
        "moon_phase": "full",
    },
    {
        "name": "Seasonal Nature Walk",
        "category": "nature",
        "tagline": "Walk the same path in every season and see four worlds",
        "description": "Walking a familiar route with the specific intention of noticing seasonal changes. The same tree looks entirely different in April, July, October, and January.",
        "duration_min": 45,
        "difficulty": "easy",
        "season": "all",
        "setting": "outdoor",
        "supplies": "Comfortable shoes, camera or notebook (optional)",
        "instructions": "1. Choose a route you can walk in every season.\n2. Walk slowly, looking specifically for signs of the current season.\n3. Notice what's blooming, fruiting, changing color, or bare.\n4. Take a photo from the same spot each season to compare.\n5. Over a year, you'll witness the full cycle of your corner of the world.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Stone Skipping",
        "category": "nature",
        "tagline": "Make the water count your tries",
        "description": "Finding flat stones and skipping them across water. An entirely purposeless, deeply satisfying activity that requires presence, aim, and the right flick of the wrist.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "summer",
        "setting": "outdoor",
        "supplies": "Flat stones, a calm body of water",
        "instructions": "1. Find a calm lake, pond, or river.\n2. Search for flat, smooth stones that fit in your palm.\n3. Stand sideways to the water and throw sidearm with a flick.\n4. Try to beat your best skip count.\n5. Enjoy the sound, the ripples, and the complete pointlessness of it all.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Garden Weeding",
        "category": "nature",
        "tagline": "Clear the ground so good things can grow",
        "description": "The meditative act of pulling weeds from a garden — slow, repetitive, and surprisingly satisfying. Each weed removed is a small act of care for the things you chose to plant.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "summer",
        "setting": "outdoor",
        "supplies": "Garden gloves, kneeling pad, bucket",
        "instructions": "1. Kneel or sit beside a section of garden.\n2. Identify the weeds — pull gently from the base to get the roots.\n3. Work in one small area before moving on.\n4. Feel the soil between your fingers.\n5. Step back when you're done and admire the cleared space.",
        "benefit": "focus",
        "moon_phase": "waning",
    },
    {
        "name": "Picnic for One",
        "category": "nature",
        "tagline": "Set a table under the open sky",
        "description": "Packing a simple meal and eating it outdoors — alone, deliberately, and without rush. A sandwich tastes different when the sky is your ceiling.",
        "duration_min": 45,
        "difficulty": "easy",
        "season": "spring",
        "setting": "outdoor",
        "supplies": "Blanket, packed meal, water bottle, a good spot",
        "instructions": "1. Pack a simple meal: a sandwich, fruit, something sweet.\n2. Find a quiet spot outdoors — a park, a riverbank, your backyard.\n3. Spread a blanket and set out your food.\n4. Eat slowly, paying attention to tastes and textures.\n5. Lie back on the blanket for a few minutes when you're done.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Thunderstorm Watching",
        "category": "nature",
        "tagline": "The sky reminds you it's alive",
        "description": "Watching a thunderstorm from a safe, sheltered spot. Lightning, thunder, wind, and rain in their full dramatic performance. Nature's most spectacular show, and the tickets are free.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "summer",
        "setting": "indoor",
        "supplies": "A window or covered porch with a view, blanket",
        "instructions": "1. When a thunderstorm approaches, find a safe viewing spot.\n2. Turn off indoor lights so you can see the lightning better.\n3. Count the seconds between lightning and thunder to gauge distance.\n4. Watch the clouds, the wind, the sheets of rain.\n5. Stay until the storm passes and notice the strange calm after.",
        "benefit": "stress",
        "moon_phase": "any",
    },

    # ── Nourish (7) ──
    {
        "name": "Slow-Cooked Soup",
        "category": "nourish",
        "tagline": "Let time be the main ingredient",
        "description": "Making a soup from scratch, slowly — chopping vegetables, building flavor, letting it simmer for as long as it needs. The kitchen fills with warmth and the house smells like home.",
        "duration_min": 90,
        "difficulty": "moderate",
        "season": "fall",
        "setting": "indoor",
        "supplies": "Fresh vegetables, broth, herbs, heavy pot, cutting board, knife",
        "instructions": "1. Choose your base: onion, garlic, celery, carrot — dice them small.\n2. Sauté the base in olive oil until soft and fragrant.\n3. Add your main vegetables and broth, bring to a gentle simmer.\n4. Season with herbs (thyme, bay leaf, black pepper) and let it cook low and slow.\n5. Taste, adjust, and serve in a bowl you love.",
        "benefit": "connection",
        "moon_phase": "full",
    },
    {
        "name": "Herbal Tea Blending",
        "category": "nourish",
        "tagline": "Compose a cup that's entirely yours",
        "description": "Creating your own tea blend from dried herbs, flowers, and spices. Chamomile and lavender for calm, ginger and lemon for energy — you become the herbalist.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Dried herbs (chamomile, lavender, peppermint, ginger), small jars, tea infuser",
        "instructions": "1. Choose a purpose for your blend: calm, energy, digestion, or warmth.\n2. Select 2-3 base herbs and one accent flavor.\n3. Mix in a small bowl, smelling as you go.\n4. Store in a labeled jar with the date.\n5. Brew a test cup and adjust ratios for next time.",
        "benefit": "joy",
        "moon_phase": "new",
    },
    {
        "name": "Bread Baking",
        "category": "nourish",
        "tagline": "Flour, water, salt, time, and your hands",
        "description": "Baking a simple loaf of bread from scratch. The kneading is meditative, the waiting is a practice in patience, and the smell of fresh bread is its own reward.",
        "duration_min": 180,
        "difficulty": "involved",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Flour, water, yeast, salt, mixing bowl, baking sheet or Dutch oven",
        "instructions": "1. Mix flour, water, yeast, and salt into a shaggy dough.\n2. Knead for 10 minutes until smooth and elastic.\n3. Cover and let rise in a warm spot for 1-2 hours.\n4. Shape the dough, place in a floured vessel, and let rise again.\n5. Bake in a preheated oven (450°F) until golden and hollow-sounding when tapped.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Seasonal Fruit Preserving",
        "category": "nourish",
        "tagline": "Capture summer in a jar",
        "description": "Making a simple jam or preserve from seasonal fruit. Strawberries in June, peaches in August, figs in September. A way to hold onto a season long after it passes.",
        "duration_min": 60,
        "difficulty": "moderate",
        "season": "summer",
        "setting": "indoor",
        "supplies": "Fresh fruit, sugar, lemon juice, heavy-bottomed pot, glass jars",
        "instructions": "1. Wash and chop your fruit, removing any stems or pits.\n2. Combine fruit, sugar, and lemon juice in a heavy pot.\n3. Cook on medium heat, stirring often, until thick and jammy (20-30 min).\n4. Test for set by placing a spoonful on a cold plate.\n5. Pour into sterilized jars and seal while hot.",
        "benefit": "joy",
        "moon_phase": "full",
    },
    {
        "name": "Meal Prep Sunday",
        "category": "nourish",
        "tagline": "A gift from today-you to tomorrow-you",
        "description": "Spending a few hours on Sunday preparing meals for the week ahead. Chopping, roasting, portioning. Future-you will be grateful every single time.",
        "duration_min": 120,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Groceries for the week, containers, cutting board, sheet pans",
        "instructions": "1. Plan 3-4 meals for the week and make a grocery list.\n2. Start with items that take longest: grains, roasted vegetables, proteins.\n3. While those cook, prep raw ingredients: wash greens, chop vegetables.\n4. Portion meals into containers, labeling with contents and date.\n5. Stack in the fridge and admire your future self's good fortune.",
        "benefit": "energy",
        "moon_phase": "waxing",
    },
    {
        "name": "Farmers Market Visit",
        "category": "nourish",
        "tagline": "Let the season choose your menu",
        "description": "Visiting a farmers market with no list — just open eyes and curiosity. Let whatever is freshest and most beautiful guide your meals for the week.",
        "duration_min": 60,
        "difficulty": "easy",
        "season": "summer",
        "setting": "outdoor",
        "supplies": "Reusable bags, cash, a good appetite for wandering",
        "instructions": "1. Arrive early for the best selection.\n2. Walk the entire market once before buying anything.\n3. Talk to the growers — ask what's at peak season.\n4. Buy one thing you've never cooked before.\n5. Plan the week's meals around what you brought home.",
        "benefit": "connection",
        "moon_phase": "any",
    },
    {
        "name": "Infused Water Crafting",
        "category": "nourish",
        "tagline": "Make hydration a small ceremony",
        "description": "Creating beautiful, flavorful infused water with fresh fruits, herbs, and edible flowers. A gentle way to drink more water and add a touch of beauty to the everyday.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "summer",
        "setting": "indoor",
        "supplies": "Glass pitcher, fresh fruit (citrus, berries), fresh herbs (mint, basil), ice",
        "instructions": "1. Choose a combination: cucumber-mint, strawberry-basil, or citrus-rosemary.\n2. Slice fruits and gently bruise herbs to release oils.\n3. Layer in a glass pitcher with ice.\n4. Fill with cold water and refrigerate for at least 30 minutes.\n5. Pour into your favorite glass and notice how much prettier water can be.",
        "benefit": "energy",
        "moon_phase": "any",
    },

    # ── Nourish (continued) ──
    {
        "name": "Smoothie Bowl Art",
        "category": "nourish",
        "tagline": "Breakfast as a canvas",
        "description": "Blending a thick smoothie base and topping it with sliced fruit, seeds, and granola arranged beautifully. Eating something you made pretty changes how it tastes.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "summer",
        "setting": "indoor",
        "supplies": "Blender, frozen fruit, banana, yogurt, toppings (granola, seeds, fresh fruit)",
        "instructions": "1. Blend frozen fruit, banana, and a splash of milk until very thick.\n2. Pour into a bowl — it should be spoonable, not drinkable.\n3. Arrange toppings in rows or patterns: sliced fruit, granola, seeds.\n4. Take a moment to admire before eating.\n5. Eat slowly, starting from one end so the design reveals itself.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Homemade Pasta",
        "category": "nourish",
        "tagline": "Flour and eggs and the work of your hands",
        "description": "Making pasta from scratch — just flour, eggs, salt, and time. The kneading and rolling are meditative. The eating is transcendent. Nothing from a box tastes like this.",
        "duration_min": 90,
        "difficulty": "involved",
        "season": "fall",
        "setting": "indoor",
        "supplies": "Flour, eggs, salt, rolling pin or pasta machine, large pot",
        "instructions": "1. Mound flour on a clean surface, make a well, crack in eggs and salt.\n2. Mix with a fork, then knead by hand for 8-10 minutes until silky.\n3. Wrap in plastic and rest for 30 minutes.\n4. Roll thin and cut into your preferred shape.\n5. Cook in boiling salted water for 2-3 minutes. Toss with butter or simple sauce.",
        "benefit": "joy",
        "moon_phase": "full",
    },
    {
        "name": "Spice Cabinet Exploration",
        "category": "nourish",
        "tagline": "Open every jar and remember what's there",
        "description": "Going through your spice collection — smelling, tasting, reorganizing. Rediscover what you already have and let a forgotten spice inspire tonight's dinner.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Your spice collection, damp cloth, labels (optional)",
        "instructions": "1. Take every spice out of the cabinet.\n2. Open each one, smell it, and taste a tiny pinch.\n3. Discard anything stale (spices lose potency after 1-2 years).\n4. Reorganize by cuisine or frequency of use.\n5. Choose one spice you haven't used lately and build dinner around it.",
        "benefit": "joy",
        "moon_phase": "waning",
    },
    {
        "name": "Chocolate Tasting",
        "category": "nourish",
        "tagline": "Two squares, tasted like they matter",
        "description": "Eating a small amount of good chocolate with full attention — the snap, the melt, the flavor notes. Mindful eating distilled to its most luxurious form.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Quality dark chocolate (2-3 varieties if possible)",
        "instructions": "1. Choose 2-3 small pieces of different chocolate.\n2. Look at the color and surface of each piece.\n3. Snap one in half and listen to the break.\n4. Place a piece on your tongue and let it melt — don't chew.\n5. Notice the flavors as they develop: fruity, nutty, bitter, sweet.",
        "benefit": "joy",
        "moon_phase": "any",
    },
    {
        "name": "Overnight Oats Prep",
        "category": "nourish",
        "tagline": "Tonight's five minutes are tomorrow's gift",
        "description": "Layering oats, milk, and toppings in a jar before bed. You wake up to a ready-made breakfast that feels like someone else made it for you. Past-you is so thoughtful.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Mason jar, rolled oats, milk or yogurt, toppings (fruit, nuts, honey)",
        "instructions": "1. Add 1/2 cup oats and 1/2 cup milk to a jar.\n2. Stir in a spoonful of yogurt, chia seeds, or nut butter.\n3. Layer with fruit, nuts, or honey.\n4. Seal and refrigerate overnight.\n5. In the morning, eat cold or warm it up. Either way, you win.",
        "benefit": "energy",
        "moon_phase": "any",
    },
    {
        "name": "Kitchen Herb Drying",
        "category": "nourish",
        "tagline": "Hang summer from the ceiling",
        "description": "Bundling fresh herbs and hanging them to dry in your kitchen. Rosemary, thyme, lavender — the kitchen becomes fragrant and beautiful, and you have dried herbs for months.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "summer",
        "setting": "indoor",
        "supplies": "Fresh herbs, kitchen twine, small hooks or nails",
        "instructions": "1. Gather fresh herbs in small bundles (5-6 stems each).\n2. Tie the stems tightly with kitchen twine.\n3. Hang upside down in a warm, dry spot with good airflow.\n4. Wait 1-2 weeks until completely dry and crumbly.\n5. Strip leaves from stems and store in labeled jars.",
        "benefit": "joy",
        "moon_phase": "waning",
    },
    {
        "name": "Mindful Cooking (One Dish Focus)",
        "category": "nourish",
        "tagline": "Cook one thing with your whole attention",
        "description": "Choosing a single dish and cooking it with complete presence — no podcast, no multitasking. Just you, the ingredients, and the process. Cooking as meditation.",
        "duration_min": 45,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Ingredients for one simple dish, kitchen tools",
        "instructions": "1. Choose a simple dish you enjoy — an omelet, a stir-fry, a salad.\n2. Turn off all background noise.\n3. Prep each ingredient with attention: the sound of chopping, the smell of garlic.\n4. Cook slowly, watching colors change and listening to the sizzle.\n5. Plate with care and eat at a table, not standing up.",
        "benefit": "focus",
        "moon_phase": "any",
    },
    {
        "name": "Fermentation Project",
        "category": "nourish",
        "tagline": "Invite tiny allies to transform your food",
        "description": "Starting a simple fermentation — sauerkraut, pickles, or kombucha. A project measured in days and weeks that teaches patience and rewards you with living food.",
        "duration_min": 30,
        "difficulty": "involved",
        "season": "fall",
        "setting": "indoor",
        "supplies": "Cabbage or vegetables, salt, mason jar, weight",
        "instructions": "1. Shred cabbage finely and massage with salt until liquid forms.\n2. Pack tightly into a clean mason jar, pressing down.\n3. Ensure the liquid covers the cabbage — weigh it down.\n4. Cover loosely and leave at room temperature for 3-7 days.\n5. Taste daily until it reaches your preferred tanginess. Refrigerate.",
        "benefit": "joy",
        "moon_phase": "waxing",
    },
    {
        "name": "Golden Milk Making",
        "category": "nourish",
        "tagline": "Warm yourself from the inside out",
        "description": "Making turmeric golden milk — a warm, spiced drink that glows like liquid sunshine. Anti-inflammatory, comforting, and beautiful in a clear mug.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Milk (any kind), turmeric, cinnamon, ginger, black pepper, honey",
        "instructions": "1. Warm a cup of milk in a small saucepan over medium heat.\n2. Add 1 tsp turmeric, 1/2 tsp cinnamon, a pinch of ginger and black pepper.\n3. Whisk gently until smooth and steaming (don't boil).\n4. Strain into a mug and stir in honey to taste.\n5. Hold with both hands and sip slowly. Notice the color.",
        "benefit": "stress",
        "moon_phase": "full",
    },

    # ── Rest (7) ──
    {
        "name": "Sleep Hygiene Ritual",
        "category": "rest",
        "tagline": "Teach your body the language of sleep",
        "description": "A consistent pre-sleep routine that signals to your nervous system that it's time to wind down. The same steps, the same order, every night. Ritual creates safety, and safety creates sleep.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Dim lighting, herbal tea, book, comfortable sleepwear",
        "instructions": "1. Set a consistent wind-down time — same time each night.\n2. Dim all lights and switch to warm, low lighting.\n3. Make a cup of caffeine-free tea (chamomile, valerian, or rooibos).\n4. Read a physical book for 15-20 minutes (no screens).\n5. Do a 2-minute body scan in bed before closing your eyes.",
        "benefit": "sleep",
        "moon_phase": "any",
    },
    {
        "name": "Power Nap Protocol",
        "category": "rest",
        "tagline": "Twenty minutes of borrowed night",
        "description": "A strategic 20-minute nap taken between 1-3 PM — long enough to restore alertness, short enough to avoid sleep inertia. A small surrender that yields big returns.",
        "duration_min": 25,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Couch or bed, blanket, eye mask (optional), alarm",
        "instructions": "1. Set an alarm for 20-25 minutes (account for falling asleep).\n2. Lie down in a slightly cool, dark space.\n3. If using a blanket, choose something light.\n4. Close your eyes and let thoughts pass without engaging.\n5. When the alarm rings, sit up slowly, stretch, and drink a glass of water.",
        "benefit": "energy",
        "moon_phase": "any",
    },
    {
        "name": "Hammock Reading",
        "category": "rest",
        "tagline": "Swing between chapters and clouds",
        "description": "Reading a book in a hammock — or any deeply comfortable, slightly swaying spot. The gentle rocking, the fresh air, the story — each one compounds the calm.",
        "duration_min": 60,
        "difficulty": "easy",
        "season": "summer",
        "setting": "outdoor",
        "supplies": "Hammock or comfortable outdoor chair, book, blanket, drink",
        "instructions": "1. Set up your hammock in a shaded spot with a breeze.\n2. Bring a book you're reading for pleasure — not productivity.\n3. Settle in with a blanket and a drink.\n4. Read without a goal — no page targets, no timers.\n5. If you fall asleep, consider that a success.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Candlelit Evening",
        "category": "rest",
        "tagline": "Let firelight soften the edges",
        "description": "Spending an evening by candlelight instead of overhead lights. The soft flicker changes everything — the room, the mood, the pace of the evening. Ancient light for modern tiredness.",
        "duration_min": 120,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Candles (several), matches, cozy blanket",
        "instructions": "1. After sunset, turn off all overhead lights.\n2. Light candles in your main living space — at least three for good light.\n3. Do your usual evening activities by candlelight: cook, read, talk.\n4. Notice how the room feels different. Notice how you feel different.\n5. Blow out the candles when you head to bed. Watch the last wisp of smoke.",
        "benefit": "stress",
        "moon_phase": "full",
    },
    {
        "name": "Screen-Free Morning",
        "category": "rest",
        "tagline": "Let the day begin with you, not a screen",
        "description": "Keeping all screens off for the first hour after waking. No email, no news, no social media. Just you, the morning, and whatever you choose to do with your first waking hour.",
        "duration_min": 60,
        "difficulty": "moderate",
        "season": "all",
        "setting": "indoor",
        "supplies": "Analog alarm clock, book, journal, coffee or tea supplies",
        "instructions": "1. The night before, charge your phone in another room.\n2. Wake with an analog alarm or sunrise alarm clock.\n3. Make coffee or tea without checking any device.\n4. Spend the first hour reading, stretching, journaling, or just sitting.\n5. Notice how differently the day begins when you choose its first input.",
        "benefit": "focus",
        "moon_phase": "new",
    },
    {
        "name": "Restorative Yoga (Legs Up the Wall)",
        "category": "rest",
        "tagline": "Do less. Way, way less.",
        "description": "A single restorative yoga pose — viparita karani — that reverses blood flow, calms the nervous system, and asks absolutely nothing of you except showing up and lying down.",
        "duration_min": 15,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Wall space, yoga mat or blanket, pillow (optional)",
        "instructions": "1. Sit sideways next to a wall, then swing your legs up as you lie back.\n2. Scoot your hips as close to the wall as comfortable.\n3. Rest your arms at your sides, palms up.\n4. Close your eyes and breathe naturally.\n5. Stay for 10-15 minutes. To come out, bend your knees and roll to one side.",
        "benefit": "sleep",
        "moon_phase": "full",
    },
    {
        "name": "Cozy Den Building",
        "category": "rest",
        "tagline": "Build yourself a nest and climb in",
        "description": "Creating a cozy corner or blanket fort for reading, resting, or just being. Pillows, blankets, fairy lights. Childlike? Yes. Necessary? Also yes.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Blankets, pillows, fairy lights (optional), books, snacks",
        "instructions": "1. Choose a corner, couch, or space that feels enclosed and safe.\n2. Layer blankets and pillows to create a soft nest.\n3. Add fairy lights or a lamp for warm, low light.\n4. Bring in a book, journal, or nothing at all.\n5. Climb in and stay as long as you want. No one needs to know.",
        "benefit": "joy",
        "moon_phase": "new",
    },
    # ── Nourish (one more) ──
    {
        "name": "Bone Broth Simmering",
        "category": "nourish",
        "tagline": "The longest, slowest recipe is the simplest",
        "description": "Making bone broth from scratch — bones, water, vinegar, time. It simmers for hours, filling the house with warmth. Liquid gold that heals and nourishes from the inside.",
        "duration_min": 240,
        "difficulty": "moderate",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Bones (chicken or beef), water, apple cider vinegar, onion, garlic, herbs, large pot",
        "instructions": "1. Place bones in a large pot and cover with cold water.\n2. Add a splash of apple cider vinegar and let sit 30 minutes.\n3. Add onion, garlic, and herbs. Bring to a gentle simmer.\n4. Cook on the lowest heat for 8-24 hours, skimming occasionally.\n5. Strain, salt to taste, and sip from a mug or use as a base for soups.",
        "benefit": "connection",
        "moon_phase": "full",
    },

    # ── Rest (continued) ──
    {
        "name": "Yoga Nidra",
        "category": "rest",
        "tagline": "Sleep while you're still awake",
        "description": "A guided deep relaxation practice done lying down — often called 'yogic sleep.' You hover between waking and sleeping while a guide leads you through body awareness and visualization.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Comfortable surface, blanket, eye mask, guided recording",
        "instructions": "1. Lie down on your back in a warm, quiet space.\n2. Cover yourself with a blanket and put on an eye mask.\n3. Play a yoga nidra recording (20-40 minutes).\n4. Follow the instructions without trying to stay awake or fall asleep.\n5. When the recording ends, lie still for a minute before slowly moving.",
        "benefit": "sleep",
        "moon_phase": "full",
    },
    {
        "name": "Slow Morning Routine",
        "category": "rest",
        "tagline": "Rush nowhere before 9 AM",
        "description": "Giving yourself a morning with no time pressure. Wake without an alarm if possible, move slowly, and do each thing — shower, dress, eat — at half speed.",
        "duration_min": 90,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "A morning with nothing scheduled early",
        "instructions": "1. The night before, clear your morning of obligations.\n2. Wake naturally or with a gentle alarm.\n3. Move through your routine at half speed — notice each step.\n4. Eat breakfast sitting down, tasting each bite.\n5. Don't check your phone until you feel fully awake and present.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Window Seat Reading",
        "category": "rest",
        "tagline": "Curl up where the light finds you",
        "description": "Reading in a window seat, a sunlit corner, or anywhere light pours in. The combination of natural light, a comfortable perch, and a good story is a simple kind of heaven.",
        "duration_min": 45,
        "difficulty": "easy",
        "season": "fall",
        "setting": "indoor",
        "supplies": "Book, cushion or blanket, a window with good light",
        "instructions": "1. Find a spot near a window where light falls.\n2. Arrange cushions or a blanket for comfort.\n3. Bring a book and a warm drink.\n4. Read without a timer or page goal.\n5. Look up from the book occasionally and watch the world outside.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Do Nothing Day",
        "category": "rest",
        "tagline": "Cancel everything and mean it",
        "description": "A full day with no plans, no productivity, no goals. Not a 'lazy day' — an intentional practice of rest. The hardest activity on this list for most people.",
        "duration_min": 480,
        "difficulty": "involved",
        "season": "all",
        "setting": "either",
        "supplies": "A cleared calendar, permission from yourself",
        "instructions": "1. Choose a day and cancel or postpone everything.\n2. When you wake up, ask: what do I feel like doing? Do that.\n3. If the answer is 'nothing,' do nothing.\n4. Resist the urge to be productive — notice the discomfort.\n5. At the end of the day, notice how rested you feel.",
        "benefit": "stress",
        "moon_phase": "new",
    },
    {
        "name": "Gentle Stretching Before Bed",
        "category": "rest",
        "tagline": "Unwind the body so the mind can follow",
        "description": "A short sequence of gentle stretches done on the floor or in bed, designed to release the physical tension of the day and prepare the body for sleep.",
        "duration_min": 10,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Bed or yoga mat, pillow",
        "instructions": "1. Sit on the edge of your bed and roll your neck gently in circles.\n2. Lie back and hug your knees to your chest, rocking side to side.\n3. Extend your legs and do a gentle spinal twist on each side.\n4. Stretch your arms overhead and take five deep breaths.\n5. Release everything and let your body sink heavy into the mattress.",
        "benefit": "sleep",
        "moon_phase": "any",
    },
    {
        "name": "Audiobook in the Dark",
        "category": "rest",
        "tagline": "Let someone else tell you a story",
        "description": "Lying in a dark room listening to an audiobook or a long-form story podcast. Like being read to as a child — someone else's voice carrying you somewhere.",
        "duration_min": 30,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Audiobook or podcast, speaker or headphones, dark room",
        "instructions": "1. Choose an audiobook or story podcast — fiction works best.\n2. Lie down in a dark room.\n3. Set a sleep timer in case you drift off (that's fine).\n4. Close your eyes and let the narrator's voice carry you.\n5. Don't worry about remembering everything. Just listen.",
        "benefit": "sleep",
        "moon_phase": "any",
    },
    {
        "name": "Afternoon Tea Ritual",
        "category": "rest",
        "tagline": "3 PM permission to pause",
        "description": "A deliberate mid-afternoon break with tea and a small treat. Not a coffee-to-keep-going break — a genuine pause. The British had this figured out all along.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Tea, a small treat (biscuit, chocolate, fruit), a nice cup",
        "instructions": "1. Around 3 PM, step away from what you're doing.\n2. Boil water and make tea with care.\n3. Set a small treat on a plate — not eaten standing up.\n4. Sit somewhere comfortable, away from your workspace.\n5. Drink and eat slowly. This is not a break from life — this is life.",
        "benefit": "energy",
        "moon_phase": "any",
    },
    {
        "name": "Cloud Couch Session",
        "category": "rest",
        "tagline": "Horizontal is a valid life choice",
        "description": "Lying on the couch under a soft blanket with absolutely no intention of doing anything. Not sleeping, not reading, not watching — just existing horizontally.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "winter",
        "setting": "indoor",
        "supplies": "Couch, soft blanket, pillow",
        "instructions": "1. Clear the couch of everything except one pillow.\n2. Lie down and pull a soft blanket over yourself.\n3. Don't pick up your phone, a book, or a remote.\n4. Stare at the ceiling, close your eyes, or look out the window.\n5. Stay until you feel like moving. There is no minimum or maximum.",
        "benefit": "stress",
        "moon_phase": "any",
    },
    {
        "name": "Weighted Blanket Rest",
        "category": "rest",
        "tagline": "Let gravity hold you",
        "description": "Lying under a weighted blanket for deep pressure stimulation — the same principle behind a good hug. The gentle, even weight calms the nervous system and slows everything down.",
        "duration_min": 20,
        "difficulty": "easy",
        "season": "all",
        "setting": "indoor",
        "supplies": "Weighted blanket (15-20 lbs), comfortable surface",
        "instructions": "1. Lie down on your back on a comfortable surface.\n2. Pull the weighted blanket over your entire body.\n3. Place your arms at your sides or on your chest.\n4. Close your eyes and breathe slowly.\n5. Stay for 15-20 minutes. Notice how the weight quiets your mind.",
        "benefit": "stress",
        "moon_phase": "full",
    },
]


def seed(db_path=None):
    """Seed the database with curated self-care activities."""
    conn = db.init_db(db_path)

    count = 0
    for entry in ACTIVITIES:
        cols = []
        placeholders = []
        values = []
        for key in (
            "name", "category", "description", "tagline", "duration_min",
            "difficulty", "season", "setting", "supplies", "instructions",
            "benefit", "moon_phase",
        ):
            if key in entry:
                cols.append(key)
                placeholders.append("?")
                values.append(entry[key])

        conn.execute(
            f"INSERT OR IGNORE INTO activities ({', '.join(cols)}) VALUES ({', '.join(placeholders)})",
            values,
        )
        count += 1

    conn.commit()
    conn.close()
    print(f"Seeded {count} activities")


if __name__ == "__main__":
    db_path = os.path.join(os.path.dirname(__file__), "self_care.db")
    if os.path.exists(db_path):
        os.remove(db_path)
    seed(db_path)
