"""Seed the NYC Film Scene Map database with venue data."""

import db

VENUES = [
    # ── Cinemas (17) ──
    {
        "name": "Anthology Film Archives",
        "category": "cinema",
        "address": "32 2nd Ave, New York, NY 10003",
        "neighborhood": "East Village",
        "borough": "Manhattan",
        "lat": 40.7247,
        "lng": -73.9908,
        "url": "https://anthologyfilmarchives.org",
        "description": "Founded by Jonas Mekas in 1970, Anthology is the world's foremost archive and theater dedicated to avant-garde and independent cinema.",
        "highlight": "Home of Essential Cinema",
    },
    {
        "name": "Metrograph",
        "category": "cinema",
        "address": "7 Ludlow St, New York, NY 10002",
        "neighborhood": "Lower East Side",
        "borough": "Manhattan",
        "lat": 40.7151,
        "lng": -73.9912,
        "url": "https://metrograph.com",
        "description": "A two-screen repertory cinema with a commissary restaurant, bookshop, and candy bar. Opened in 2016.",
        "highlight": "Repertory + new releases",
    },
    {
        "name": "IFC Center",
        "category": "cinema",
        "address": "323 6th Ave, New York, NY 10014",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7312,
        "lng": -74.0017,
        "url": "https://www.ifccenter.com",
        "description": "Five-screen art house in the former Waverly Theatre. Programs independent, foreign, and classic films.",
        "highlight": "Late-night cult screenings",
    },
    {
        "name": "Film Forum",
        "category": "cinema",
        "address": "209 W Houston St, New York, NY 10014",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7275,
        "lng": -74.0044,
        "url": "https://filmforum.org",
        "description": "NYC's leading nonprofit cinema since 1970. Three screens showing premieres, repertory, and restorations.",
        "highlight": "NYC's longest-running indie cinema",
    },
    {
        "name": "BAM Rose Cinemas",
        "category": "cinema",
        "address": "30 Lafayette Ave, Brooklyn, NY 11217",
        "neighborhood": "Fort Greene",
        "borough": "Brooklyn",
        "lat": 40.6862,
        "lng": -73.9782,
        "url": "https://www.bam.org",
        "description": "Four-screen cinema inside the Brooklyn Academy of Music's Peter Jay Sharp building. Hosts BAMcinématek.",
        "highlight": "BAMcinématek retrospectives",
    },
    {
        "name": "Roxy Cinema",
        "category": "cinema",
        "address": "2 6th Ave, New York, NY 10013",
        "neighborhood": "Tribeca",
        "borough": "Manhattan",
        "lat": 40.7195,
        "lng": -74.0047,
        "url": "https://roxycinema.com",
        "description": "Boutique cinema in the Roxy Hotel Tribeca. Single-screen theater with plush seating and curated programming.",
        "highlight": "Hotel cinema with style",
    },
    {
        "name": "Cinema Village",
        "category": "cinema",
        "address": "22 E 12th St, New York, NY 10003",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7337,
        "lng": -73.9956,
        "url": "https://cinemavillage.com",
        "description": "Three-screen independent movie theater in a converted firehouse. One of NYC's oldest continuously operating cinemas.",
        "highlight": "Converted 1890s firehouse",
    },
    {
        "name": "Spectacle Theater",
        "category": "cinema",
        "address": "124 S 3rd St, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7125,
        "lng": -73.9633,
        "url": "https://spectacletheater.com",
        "description": "Volunteer-run microcinema in Williamsburg showing obscure, underground, and experimental films. Cash-only, BYO snacks.",
        "highlight": "Volunteer-run underground gem",
    },
    {
        "name": "Nitehawk Cinema",
        "category": "cinema",
        "address": "136 Metropolitan Ave, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7160,
        "lng": -73.9618,
        "url": "https://nitehawkcinema.com",
        "description": "Dine-in cinema with a focus on indie, cult, and repertory programming. Full food and drink service at your seat.",
        "highlight": "Dine-in indie cinema",
    },
    {
        "name": "Museum of the Moving Image",
        "category": "cinema",
        "address": "36-01 35th Ave, Queens, NY 11106",
        "neighborhood": "Astoria",
        "borough": "Queens",
        "lat": 40.7564,
        "lng": -73.9237,
        "url": "https://movingimage.us",
        "description": "Museum and cinema dedicated to the art, history, and technology of the moving image. Houses a major collection of film artifacts.",
        "highlight": "Film history + screenings",
    },
    {
        "name": "Film at Lincoln Center",
        "category": "cinema",
        "address": "165 W 65th St, New York, NY 10023",
        "neighborhood": "Upper West Side",
        "borough": "Manhattan",
        "lat": 40.7736,
        "lng": -73.9835,
        "url": "https://www.filmlinc.org",
        "description": "Home of the New York Film Festival and year-round repertory and premiere programming at the Elinor Bunin Munroe Film Center.",
        "highlight": "Home of NYFF",
    },
    {
        "name": "Quad Cinema",
        "category": "cinema",
        "address": "34 W 13th St, New York, NY 10011",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7360,
        "lng": -73.9961,
        "url": "https://quadcinema.com",
        "description": "Renovated four-screen cinema in Greenwich Village. First US multiplex when it opened in 1972, now shows curated indie and arthouse.",
        "highlight": "America's first multiplex",
    },
    {
        "name": "Light Industry",
        "category": "cinema",
        "address": "155 Freeman St, Brooklyn, NY 11222",
        "neighborhood": "Greenpoint",
        "borough": "Brooklyn",
        "lat": 40.7318,
        "lng": -73.9557,
        "url": "https://lightindustry.org",
        "description": "Venue for film and electronic art in Greenpoint. Regular screenings of experimental, artist, and repertory cinema.",
        "highlight": "Film + electronic art screenings",
    },
    {
        "name": "Angelika Film Center",
        "category": "cinema",
        "address": "18 W Houston St, New York, NY 10012",
        "neighborhood": "SoHo",
        "borough": "Manhattan",
        "lat": 40.7257,
        "lng": -73.9996,
        "url": "https://angelikafilmcenter.com",
        "description": "Six-screen art house cinema at the corner of Houston and Mercer. A staple for independent and foreign film since 1989.",
        "highlight": "Iconic indie cinema since '89",
    },
    {
        "name": "Paris Theater",
        "category": "cinema",
        "address": "4 W 58th St, New York, NY 10019",
        "neighborhood": "Midtown",
        "borough": "Manhattan",
        "lat": 40.7645,
        "lng": -73.9741,
        "url": "https://paristheaternyc.com",
        "description": "Single-screen cinema across from the Plaza Hotel. Opened in 1948, it is one of the last remaining single-screen cinemas in NYC.",
        "highlight": "Historic single-screen gem",
    },
    {
        "name": "Alamo Drafthouse Lower Manhattan",
        "category": "cinema",
        "address": "28 Liberty St, New York, NY 10005",
        "neighborhood": "FiDi",
        "borough": "Manhattan",
        "lat": 40.7084,
        "lng": -74.0088,
        "url": "https://drafthouse.com/nyc",
        "description": "Dine-in cinema chain known for strict no-talking policy and creative programming including sing-alongs, quote-alongs, and themed events.",
        "highlight": "Dine-in + no-talking policy",
    },
    {
        "name": "Nitehawk Prospect Park",
        "category": "cinema",
        "address": "188 Prospect Park West, Brooklyn, NY 11215",
        "neighborhood": "Park Slope",
        "borough": "Brooklyn",
        "lat": 40.6616,
        "lng": -73.9808,
        "url": "https://nitehawkcinema.com/prospectpark",
        "description": "Second Nitehawk location in the landmarked Pavilion Theater. Dine-in cinema with seven screens and a rooftop bar.",
        "highlight": "Landmarked dine-in cinema",
    },
    # ── Labs (5) ──
    {
        "name": "Negativeland",
        "category": "lab",
        "address": "1717 Troutman St #244, Ridgewood, NY 11385",
        "neighborhood": "Ridgewood",
        "borough": "Queens",
        "lat": 40.7070,
        "lng": -73.9070,
        "url": "https://negativeland.com",
        "description": "Analog film lab specializing in 16mm and Super 8 processing, scanning, and printing. Artist-run and community-oriented.",
        "highlight": "Artist-run 16mm lab",
    },
    {
        "name": "Bushwick Community Darkroom",
        "category": "lab",
        "address": "334 Himrod St, Brooklyn, NY 11237",
        "neighborhood": "Bushwick",
        "borough": "Brooklyn",
        "lat": 40.7033,
        "lng": -73.9190,
        "url": "https://bushwickcommunitydarkroom.com",
        "description": "Shared darkroom and community space for analog photography. Offers memberships, workshops, and open lab hours.",
        "highlight": "Community darkroom access",
    },
    {
        "name": "Mono No Aware",
        "category": "lab",
        "address": "33 Flatbush Ave, 3rd Fl, Brooklyn, NY 11217",
        "neighborhood": "Fort Greene",
        "borough": "Brooklyn",
        "lat": 40.6858,
        "lng": -73.9789,
        "url": "https://www.monoaware.com",
        "description": "Artist-run space dedicated to the moving image, with facilities for film processing, optical printing, and expanded cinema. Also offers workshops in hand-processing, cameraless filmmaking, and expanded cinema techniques.",
        "highlight": "Expanded cinema + processing",
    },
    {
        "name": "Metropolis Post",
        "category": "lab",
        "address": "115 W 30th St, 12th Fl, New York, NY 10001",
        "neighborhood": "Midtown",
        "borough": "Manhattan",
        "lat": 40.7476,
        "lng": -73.9912,
        "url": "https://metropolispost.com",
        "description": "Full-service post-production facility with film scanning, color grading, and finishing services for independent filmmakers.",
        "highlight": "Pro post-production",
    },
    {
        "name": "Gowanus Darkroom",
        "category": "lab",
        "address": "119 8th St, Brooklyn, NY 11215",
        "neighborhood": "Gowanus",
        "borough": "Brooklyn",
        "lat": 40.6727,
        "lng": -73.9862,
        "url": "https://gowanusdarkroom.com",
        "description": "Community darkroom offering memberships, classes, and open lab time for black-and-white and color analog photography.",
        "highlight": "Community analog photo lab",
    },
    # ── Galleries (6) ──
    {
        "name": "MoMA",
        "category": "gallery",
        "address": "11 W 53rd St, New York, NY 10019",
        "neighborhood": "Midtown",
        "borough": "Manhattan",
        "lat": 40.7614,
        "lng": -73.9776,
        "url": "https://www.moma.org",
        "description": "The Museum of Modern Art's film department is one of the world's great film archives, with regular screenings in its theaters.",
        "highlight": "World-class film archive",
    },
    {
        "name": "Whitney Museum",
        "category": "gallery",
        "address": "99 Gansevoort St, New York, NY 10014",
        "neighborhood": "Meatpacking District",
        "borough": "Manhattan",
        "lat": 40.7396,
        "lng": -74.0089,
        "url": "https://whitney.org",
        "description": "American art museum with a strong focus on moving image and media art. Regular film and video installations and screenings.",
        "highlight": "Moving image + media art",
    },
    {
        "name": "New Museum",
        "category": "gallery",
        "address": "235 Bowery, New York, NY 10002",
        "neighborhood": "Lower East Side",
        "borough": "Manhattan",
        "lat": 40.7223,
        "lng": -73.9930,
        "url": "https://www.newmuseum.org",
        "description": "Contemporary art museum on the Bowery. Frequently exhibits video and moving image work by emerging artists.",
        "highlight": "Contemporary video art",
    },
    {
        "name": "Artists Space",
        "category": "gallery",
        "address": "11 Cortlandt Alley, New York, NY 10013",
        "neighborhood": "Tribeca",
        "borough": "Manhattan",
        "lat": 40.7167,
        "lng": -74.0028,
        "url": "https://artistsspace.org",
        "description": "Nonprofit gallery founded in 1972. Has long supported experimental film and video work alongside visual arts.",
        "highlight": "Experimental film + art since '72",
    },
    {
        "name": "Brooklyn Museum",
        "category": "gallery",
        "address": "200 Eastern Pkwy, Brooklyn, NY 11238",
        "neighborhood": "Prospect Heights",
        "borough": "Brooklyn",
        "lat": 40.6713,
        "lng": -73.9636,
        "url": "https://www.brooklynmuseum.org",
        "description": "Major art museum with a growing film and video art program. Hosts screenings, installations, and artist talks.",
        "highlight": "Film + video art programs",
    },
    {
        "name": "Amant",
        "category": "gallery",
        "address": "315 Maujer St, Brooklyn, NY 11206",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7081,
        "lng": -73.9432,
        "url": "https://amant.org",
        "description": "Arts campus in Williamsburg with galleries, a screening room, and artist residencies. Programs film and moving image exhibitions.",
        "highlight": "Arts campus + screening room",
    },
    # ── Organizations (6) ──
    {
        "name": "Film-Makers' Cooperative",
        "category": "organization",
        "address": "475 Park Ave S, New York, NY 10016",
        "neighborhood": "Murray Hill",
        "borough": "Manhattan",
        "lat": 40.7465,
        "lng": -73.9812,
        "url": "https://film-makerscoop.com",
        "description": "The oldest and largest archive and distributor of independent and avant-garde film in the world. Founded in 1962.",
        "highlight": "World's largest avant-garde archive",
    },
    {
        "name": "Screen Slate",
        "category": "organization",
        "address": "Brooklyn, NY",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7081,
        "lng": -73.9571,
        "url": "https://www.screenslate.com",
        "description": "NYC's essential guide to repertory, independent, and experimental film screenings. Online publication and community resource.",
        "highlight": "NYC screening guide",
    },
    {
        "name": "Analog Film NYC",
        "category": "organization",
        "address": "Brooklyn, NY",
        "neighborhood": "Bushwick",
        "borough": "Brooklyn",
        "lat": 40.6985,
        "lng": -73.9210,
        "url": "https://www.analogfilmnyc.com",
        "description": "Community organization promoting analog filmmaking in New York City through events, screenings, and shared resources.",
        "highlight": "Analog film community",
    },
    {
        "name": "Electronic Arts Intermix",
        "category": "organization",
        "address": "535 W 22nd St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough": "Manhattan",
        "lat": 40.7484,
        "lng": -74.0050,
        "url": "https://www.eai.org",
        "description": "Nonprofit resource for video and media art. Distributes and preserves a major collection of artist-made video works.",
        "highlight": "Video art distribution hub",
    },
    {
        "name": "Gotham Film & Media Institute",
        "category": "organization",
        "address": "30 John St, New York, NY 10038",
        "neighborhood": "FiDi",
        "borough": "Manhattan",
        "lat": 40.7088,
        "lng": -74.0060,
        "url": "https://gotham.pro",
        "description": "Formerly IFP. Nonprofit supporting independent filmmakers through labs, fiscal sponsorship, and the Gotham Awards.",
        "highlight": "Gotham Awards + filmmaker labs",
    },
    {
        "name": "New York Women in Film & TV",
        "category": "organization",
        "address": "6 E 39th St, New York, NY 10016",
        "neighborhood": "Midtown",
        "borough": "Manhattan",
        "lat": 40.7515,
        "lng": -73.9812,
        "url": "https://www.nywift.org",
        "description": "Nonprofit supporting women and gender-nonconforming professionals in film, TV, and digital media through networking, panels, and grants.",
        "highlight": "Women in film advocacy",
    },
    # ── Workshops (5) ──
    {
        "name": "Millennium Film Workshop",
        "category": "workshop",
        "address": "167 Wilson Ave, Brooklyn, NY 11237",
        "neighborhood": "Bushwick",
        "borough": "Brooklyn",
        "lat": 40.6982,
        "lng": -73.9234,
        "url": "https://millenniumfilm.org",
        "description": "Historic artist-run center for experimental film. Offers equipment access, screening space, and filmmaking workshops.",
        "highlight": "Historic experimental film center",
    },
    {
        "name": "NYU Tisch School of the Arts",
        "category": "workshop",
        "address": "721 Broadway, New York, NY 10003",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7290,
        "lng": -73.9938,
        "url": "https://tisch.nyu.edu",
        "description": "NYU's film school hosts public screenings, visiting artist talks, and occasional open workshops on experimental filmmaking.",
        "highlight": "Public screenings + talks",
    },
    {
        "name": "DCTV",
        "category": "workshop",
        "address": "87 Lafayette St, New York, NY 10013",
        "neighborhood": "Chinatown",
        "borough": "Manhattan",
        "lat": 40.7178,
        "lng": -73.9999,
        "url": "https://dctvny.org",
        "description": "Downtown Community Television Center. Nonprofit media center offering production classes, equipment rental, and screening space.",
        "highlight": "Community media center",
    },
    {
        "name": "UnionDocs",
        "category": "workshop",
        "address": "322 Union Ave, Brooklyn, NY 11211",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7063,
        "lng": -73.9510,
        "url": "https://uniondocs.org",
        "description": "Center for documentary art. Offers collaborative programs, artist residencies, workshops, and a regular screening series.",
        "highlight": "Documentary art center",
    },
    {
        "name": "SVA (School of Visual Arts)",
        "category": "workshop",
        "address": "209 E 23rd St, New York, NY 10010",
        "neighborhood": "Gramercy",
        "borough": "Manhattan",
        "lat": 40.7388,
        "lng": -73.9825,
        "url": "https://sva.edu",
        "description": "Art and design college with BFA/MFA programs in film and animation. Hosts public screenings, visiting artist events, and open workshops.",
        "highlight": "Film + animation programs",
    },
]


def seed():
    """Create tables and insert seed venues."""
    conn = db.init_db()
    # Clear existing data
    conn.execute("DELETE FROM venues")
    for v in VENUES:
        conn.execute(
            """INSERT INTO venues (name, category, address, neighborhood, borough,
                                   lat, lng, url, description, highlight, status)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active')""",
            (
                v["name"],
                v["category"],
                v.get("address"),
                v.get("neighborhood"),
                v.get("borough"),
                v["lat"],
                v["lng"],
                v.get("url"),
                v.get("description"),
                v.get("highlight"),
            ),
        )
    conn.commit()
    count = conn.execute("SELECT COUNT(*) FROM venues").fetchone()[0]
    print(f"Seeded {count} venues.")
    conn.close()


if __name__ == "__main__":
    seed()
