"""Seed the NYC Film Scene Map database with venue data."""

import db

VENUES = [
    # ── Cinemas (20) ──
    {
        "name": "Anthology Film Archives",
        "category": "cinema",
        "address": "32 2nd Ave, New York, NY 10003",
        "neighborhood": "East Village",
        "borough": "Manhattan",
        "lat": 40.7247,
        "lng": -73.9908,
        "url": "https://anthologyfilmarchives.org",
        "description": "Founded by Jonas Mekas in 1970, Anthology is the world's foremost archive and theater dedicated to avant-garde and independent cinema.",
        "highlight": "Home of Essential Cinema",
    },
    {
        "name": "Metrograph",
        "category": "cinema",
        "address": "7 Ludlow St, New York, NY 10002",
        "neighborhood": "Lower East Side",
        "borough": "Manhattan",
        "lat": 40.7151,
        "lng": -73.9912,
        "url": "https://metrograph.com",
        "description": "A two-screen repertory cinema with a commissary restaurant, bookshop, and candy bar. Opened in 2016.",
        "highlight": "Repertory + new releases",
    },
    {
        "name": "IFC Center",
        "category": "cinema",
        "address": "323 6th Ave, New York, NY 10014",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7312,
        "lng": -74.0017,
        "url": "https://www.ifccenter.com",
        "description": "Five-screen art house in the former Waverly Theatre. Programs independent, foreign, and classic films.",
        "highlight": "Late-night cult screenings",
    },
    {
        "name": "Film Forum",
        "category": "cinema",
        "address": "209 W Houston St, New York, NY 10014",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7275,
        "lng": -74.0044,
        "url": "https://filmforum.org",
        "description": "NYC's leading nonprofit cinema since 1970. Three screens showing premieres, repertory, and restorations.",
        "highlight": "NYC's longest-running indie cinema",
    },
    {
        "name": "BAM Rose Cinemas",
        "category": "cinema",
        "address": "30 Lafayette Ave, Brooklyn, NY 11217",
        "neighborhood": "Fort Greene",
        "borough": "Brooklyn",
        "lat": 40.6862,
        "lng": -73.9782,
        "url": "https://www.bam.org",
        "description": "Four-screen cinema inside the Brooklyn Academy of Music's Peter Jay Sharp building. Hosts BAMcinématek.",
        "highlight": "BAMcinématek retrospectives",
    },
    {
        "name": "Roxy Cinema",
        "category": "cinema",
        "address": "2 6th Ave, New York, NY 10013",
        "neighborhood": "Tribeca",
        "borough": "Manhattan",
        "lat": 40.7195,
        "lng": -74.0047,
        "url": "https://roxycinema.com",
        "description": "Boutique cinema in the Roxy Hotel Tribeca. Single-screen theater with plush seating and curated programming.",
        "highlight": "Hotel cinema with style",
    },
    {
        "name": "Cinema Village",
        "category": "cinema",
        "address": "22 E 12th St, New York, NY 10003",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7337,
        "lng": -73.9956,
        "url": "https://cinemavillage.com",
        "description": "Three-screen independent movie theater in a converted firehouse. One of NYC's oldest continuously operating cinemas.",
        "highlight": "Converted 1890s firehouse",
    },
    {
        "name": "Spectacle Theater",
        "category": "cinema",
        "address": "124 S 3rd St, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7125,
        "lng": -73.9633,
        "url": "https://spectacletheater.com",
        "description": "Volunteer-run microcinema in Williamsburg showing obscure, underground, and experimental films. Cash-only, BYO snacks.",
        "highlight": "Volunteer-run underground gem",
    },
    {
        "name": "Nitehawk Cinema",
        "category": "cinema",
        "address": "136 Metropolitan Ave, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7160,
        "lng": -73.9618,
        "url": "https://nitehawkcinema.com",
        "description": "Dine-in cinema with a focus on indie, cult, and repertory programming. Full food and drink service at your seat.",
        "highlight": "Dine-in indie cinema",
    },
    {
        "name": "Museum of the Moving Image",
        "category": "cinema",
        "address": "36-01 35th Ave, Queens, NY 11106",
        "neighborhood": "Astoria",
        "borough": "Queens",
        "lat": 40.7564,
        "lng": -73.9237,
        "url": "https://movingimage.us",
        "description": "Museum and cinema dedicated to the art, history, and technology of the moving image. Houses a major collection of film artifacts.",
        "highlight": "Film history + screenings",
    },
    {
        "name": "Film at Lincoln Center",
        "category": "cinema",
        "address": "165 W 65th St, New York, NY 10023",
        "neighborhood": "Upper West Side",
        "borough": "Manhattan",
        "lat": 40.7736,
        "lng": -73.9835,
        "url": "https://www.filmlinc.org",
        "description": "Home of the New York Film Festival and year-round repertory and premiere programming at the Elinor Bunin Munroe Film Center.",
        "highlight": "Home of NYFF",
    },
    {
        "name": "Quad Cinema",
        "category": "cinema",
        "address": "34 W 13th St, New York, NY 10011",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7360,
        "lng": -73.9961,
        "url": "https://quadcinema.com",
        "description": "Renovated four-screen cinema in Greenwich Village. First US multiplex when it opened in 1972, now shows curated indie and arthouse.",
        "highlight": "America's first multiplex",
    },
    {
        "name": "Light Industry",
        "category": "cinema",
        "address": "155 Freeman St, Brooklyn, NY 11222",
        "neighborhood": "Greenpoint",
        "borough": "Brooklyn",
        "lat": 40.7318,
        "lng": -73.9557,
        "url": "https://lightindustry.org",
        "description": "Venue for film and electronic art in Greenpoint. Regular screenings of experimental, artist, and repertory cinema.",
        "highlight": "Film + electronic art screenings",
    },
    {
        "name": "Angelika Film Center",
        "category": "cinema",
        "address": "18 W Houston St, New York, NY 10012",
        "neighborhood": "SoHo",
        "borough": "Manhattan",
        "lat": 40.7257,
        "lng": -73.9996,
        "url": "https://angelikafilmcenter.com",
        "description": "Six-screen art house cinema at the corner of Houston and Mercer. A staple for independent and foreign film since 1989.",
        "highlight": "Iconic indie cinema since '89",
    },
    {
        "name": "Paris Theater",
        "category": "cinema",
        "address": "4 W 58th St, New York, NY 10019",
        "neighborhood": "Midtown",
        "borough": "Manhattan",
        "lat": 40.7645,
        "lng": -73.9741,
        "url": "https://paristheaternyc.com",
        "description": "Single-screen cinema across from the Plaza Hotel. Opened in 1948, it is one of the last remaining single-screen cinemas in NYC.",
        "highlight": "Historic single-screen gem",
    },
    {
        "name": "Alamo Drafthouse Lower Manhattan",
        "category": "cinema",
        "address": "28 Liberty St, New York, NY 10005",
        "neighborhood": "FiDi",
        "borough": "Manhattan",
        "lat": 40.7084,
        "lng": -74.0088,
        "url": "https://drafthouse.com/nyc",
        "description": "Dine-in cinema chain known for strict no-talking policy and creative programming including sing-alongs, quote-alongs, and themed events.",
        "highlight": "Dine-in + no-talking policy",
    },
    {
        "name": "Nitehawk Prospect Park",
        "category": "cinema",
        "address": "188 Prospect Park West, Brooklyn, NY 11215",
        "neighborhood": "Park Slope",
        "borough": "Brooklyn",
        "lat": 40.6616,
        "lng": -73.9808,
        "url": "https://nitehawkcinema.com/prospectpark",
        "description": "Second Nitehawk location in the landmarked Pavilion Theater. Dine-in cinema with seven screens and a rooftop bar.",
        "highlight": "Landmarked dine-in cinema",
    },
    {
        "name": "Syndicated Bar Theater Kitchen",
        "category": "cinema",
        "address": "40 Bogart St, Brooklyn, NY 11206",
        "neighborhood": "East Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7050,
        "lng": -73.9331,
        "url": "https://syndicatedbk.com",
        "description": "A cinema-restaurant-bar hybrid where you can enjoy craft cocktails and food while watching indie and classic films in a 60-seat theater.",
        "highlight": "Eat, drink, watch films",
    },
    {
        "name": "Film Noir Cinema",
        "category": "cinema",
        "address": "122 Meserole Ave, Brooklyn, NY 11222",
        "neighborhood": "Greenpoint",
        "borough": "Brooklyn",
        "lat": 40.7274,
        "lng": -73.9517,
        "url": "https://www.filmnoircinema.com",
        "description": "An intimate 54-seat microcinema in Greenpoint screening art house, classic, and repertory films in a cozy neighborhood setting.",
        "highlight": "Tiny art house gem",
    },
    {
        "name": "Maysles Documentary Center",
        "category": "cinema",
        "address": "343 Lenox Ave, New York, NY 10027",
        "neighborhood": "Harlem",
        "borough": "Manhattan",
        "lat": 40.8093,
        "lng": -73.9445,
        "url": "https://www.maysles.org",
        "description": "Founded by legendary documentarian Albert Maysles, this Harlem cinema and community center is dedicated to documentary film exhibition, education, and production.",
        "highlight": "Harlem's documentary home",
    },
    # ── Labs (8) ──
    {
        "name": "Negativeland",
        "category": "lab",
        "address": "1717 Troutman St #244, Ridgewood, NY 11385",
        "neighborhood": "Ridgewood",
        "borough": "Queens",
        "lat": 40.7070,
        "lng": -73.9070,
        "url": "https://negativeland.com",
        "description": "Analog film lab specializing in 16mm and Super 8 processing, scanning, and printing. Artist-run and community-oriented.",
        "highlight": "Artist-run 16mm lab",
    },
    {
        "name": "Bushwick Community Darkroom",
        "category": "lab",
        "address": "334 Himrod St, Brooklyn, NY 11237",
        "neighborhood": "Bushwick",
        "borough": "Brooklyn",
        "lat": 40.7033,
        "lng": -73.9190,
        "url": "https://bushwickcommunitydarkroom.com",
        "description": "Shared darkroom and community space for analog photography. Offers memberships, workshops, and open lab hours.",
        "highlight": "Community darkroom access",
    },
    {
        "name": "Mono No Aware",
        "category": "lab",
        "address": "33 Flatbush Ave, 3rd Fl, Brooklyn, NY 11217",
        "neighborhood": "Fort Greene",
        "borough": "Brooklyn",
        "lat": 40.6858,
        "lng": -73.9789,
        "url": "https://www.monoaware.com",
        "description": "Artist-run space dedicated to the moving image, with facilities for film processing, optical printing, and expanded cinema. Also offers workshops in hand-processing, cameraless filmmaking, and expanded cinema techniques.",
        "highlight": "Expanded cinema + processing",
    },
    {
        "name": "Metropolis Post",
        "category": "lab",
        "address": "115 W 30th St, 12th Fl, New York, NY 10001",
        "neighborhood": "Midtown",
        "borough": "Manhattan",
        "lat": 40.7476,
        "lng": -73.9912,
        "url": "https://metropolispost.com",
        "description": "Full-service post-production facility with film scanning, color grading, and finishing services for independent filmmakers.",
        "highlight": "Pro post-production",
    },
    {
        "name": "Gowanus Darkroom",
        "category": "lab",
        "address": "119 8th St, Brooklyn, NY 11215",
        "neighborhood": "Gowanus",
        "borough": "Brooklyn",
        "lat": 40.6727,
        "lng": -73.9862,
        "url": "https://gowanusdarkroom.com",
        "description": "Community darkroom offering memberships, classes, and open lab time for black-and-white and color analog photography.",
        "highlight": "Community analog photo lab",
    },
    {
        "name": "Picturehouse + The Small Darkroom",
        "category": "lab",
        "address": "437 W 16th St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough": "Manhattan",
        "lat": 40.7433,
        "lng": -74.0066,
        "url": "https://phtsdr.com",
        "description": "A Chelsea-based professional analog film lab offering drum scanning, C-type printing, fine-art pigment printing, and B&W fiber printing for photographers and filmmakers.",
        "highlight": "Analog craft perfected",
    },
    {
        "name": "NYC Film Lab",
        "category": "lab",
        "address": "321 Starr St, Suite E, Brooklyn, NY 11237",
        "neighborhood": "Bushwick",
        "borough": "Brooklyn",
        "lat": 40.7075,
        "lng": -73.9209,
        "url": "https://nycfilmlab.com",
        "description": "A Bushwick analog film lab offering C-41, E-6, and B&W development plus high-quality scanning, beloved by the NYC film photography community.",
        "highlight": "Bushwick's film hub",
    },
    {
        "name": "AlterWork Studios",
        "category": "lab",
        "address": "40-20 22nd St, Long Island City, NY 11101",
        "neighborhood": "Long Island City",
        "borough": "Queens",
        "lat": 40.7545,
        "lng": -73.9406,
        "url": "https://www.alterworkstudios.com",
        "description": "A multidisciplinary shared creative workspace in LIC offering artist studios, workshops, and classes in photography, printmaking, and other media.",
        "highlight": "Create together in LIC",
    },
    # ── Museums (10) ──
    {
        "name": "MoMA",
        "category": "museum",
        "address": "11 W 53rd St, New York, NY 10019",
        "neighborhood": "Midtown",
        "borough": "Manhattan",
        "lat": 40.7614,
        "lng": -73.9776,
        "url": "https://www.moma.org",
        "description": "The Museum of Modern Art's film department is one of the world's great film archives, with regular screenings in its theaters.",
        "highlight": "World-class film archive",
    },
    {
        "name": "Whitney Museum",
        "category": "museum",
        "address": "99 Gansevoort St, New York, NY 10014",
        "neighborhood": "Meatpacking District",
        "borough": "Manhattan",
        "lat": 40.7396,
        "lng": -74.0089,
        "url": "https://whitney.org",
        "description": "American art museum with a strong focus on moving image and media art. Regular film and video installations and screenings.",
        "highlight": "Moving image + media art",
    },
    {
        "name": "New Museum",
        "category": "museum",
        "address": "235 Bowery, New York, NY 10002",
        "neighborhood": "Lower East Side",
        "borough": "Manhattan",
        "lat": 40.7223,
        "lng": -73.9930,
        "url": "https://www.newmuseum.org",
        "description": "Contemporary art museum on the Bowery. Frequently exhibits video and moving image work by emerging artists.",
        "highlight": "Contemporary video art",
    },
    {
        "name": "Artists Space",
        "category": "museum",
        "address": "11 Cortlandt Alley, New York, NY 10013",
        "neighborhood": "Tribeca",
        "borough": "Manhattan",
        "lat": 40.7167,
        "lng": -74.0028,
        "url": "https://artistsspace.org",
        "description": "Nonprofit gallery founded in 1972. Has long supported experimental film and video work alongside visual arts.",
        "highlight": "Experimental film + art since '72",
    },
    {
        "name": "Brooklyn Museum",
        "category": "museum",
        "address": "200 Eastern Pkwy, Brooklyn, NY 11238",
        "neighborhood": "Prospect Heights",
        "borough": "Brooklyn",
        "lat": 40.6713,
        "lng": -73.9636,
        "url": "https://www.brooklynmuseum.org",
        "description": "Major art museum with a growing film and video art program. Hosts screenings, installations, and artist talks.",
        "highlight": "Film + video art programs",
    },
    {
        "name": "Amant",
        "category": "museum",
        "address": "315 Maujer St, Brooklyn, NY 11206",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7081,
        "lng": -73.9432,
        "url": "https://amant.org",
        "description": "Arts campus in Williamsburg with galleries, a screening room, and artist residencies. Programs film and moving image exhibitions.",
        "highlight": "Arts campus + screening room",
    },
    {
        "name": "Pioneer Works",
        "category": "museum",
        "address": "159 Pioneer St, Brooklyn, NY 11231",
        "neighborhood": "Red Hook",
        "borough": "Brooklyn",
        "lat": 40.6794,
        "lng": -74.0118,
        "url": "https://pioneerworks.org",
        "description": "A 25,000 sq ft cultural center in a converted Red Hook warehouse fostering art, science, music, and technology through exhibitions, residencies, and free public programs.",
        "highlight": "Art meets science",
    },
    {
        "name": "Dia Chelsea",
        "category": "museum",
        "address": "537 W 22nd St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough": "Manhattan",
        "lat": 40.7473,
        "lng": -74.0052,
        "url": "https://www.diaart.org",
        "description": "A major contemporary art gallery in Chelsea showcasing large-scale installations and long-term single-artist exhibitions with free admission.",
        "highlight": "Monumental art, free entry",
    },
    {
        "name": "ICP (International Center of Photography)",
        "category": "museum",
        "address": "79 Essex St, New York, NY 10002",
        "neighborhood": "Lower East Side",
        "borough": "Manhattan",
        "lat": 40.7180,
        "lng": -73.9886,
        "url": "https://www.icp.org",
        "description": "The world's leading institution dedicated to photography and visual culture, featuring museum exhibitions, an acclaimed school, darkrooms, and media labs.",
        "highlight": "Photography's global epicenter",
    },
    {
        "name": "MoMA PS1",
        "category": "museum",
        "address": "22-25 Jackson Ave, Long Island City, NY 11101",
        "neighborhood": "Long Island City",
        "borough": "Queens",
        "lat": 40.7453,
        "lng": -73.9472,
        "url": "https://www.momaps1.org",
        "description": "One of the largest nonprofit contemporary art institutions in the US, affiliated with MoMA, housed in a former public school and known for experimental exhibitions.",
        "highlight": "Contemporary art powerhouse",
    },
    # ── Organizations (10) ──
    {
        "name": "Film-Makers' Cooperative",
        "category": "organization",
        "address": "475 Park Ave S, New York, NY 10016",
        "neighborhood": "Murray Hill",
        "borough": "Manhattan",
        "lat": 40.7465,
        "lng": -73.9812,
        "url": "https://film-makerscoop.com",
        "description": "The oldest and largest archive and distributor of independent and avant-garde film in the world. Founded in 1962.",
        "highlight": "World's largest avant-garde archive",
    },
    {
        "name": "Screen Slate",
        "category": "organization",
        "address": "Brooklyn, NY",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7081,
        "lng": -73.9571,
        "url": "https://www.screenslate.com",
        "description": "NYC's essential guide to repertory, independent, and experimental film screenings. Online publication and community resource.",
        "highlight": "NYC screening guide",
    },
    {
        "name": "Analog Film NYC",
        "category": "organization",
        "address": "Brooklyn, NY",
        "neighborhood": "Bushwick",
        "borough": "Brooklyn",
        "lat": 40.6985,
        "lng": -73.9210,
        "url": "https://www.analogfilmnyc.com",
        "description": "Community organization promoting analog filmmaking in New York City through events, screenings, and shared resources.",
        "highlight": "Analog film community",
    },
    {
        "name": "Electronic Arts Intermix",
        "category": "organization",
        "address": "535 W 22nd St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough": "Manhattan",
        "lat": 40.7484,
        "lng": -74.0050,
        "url": "https://www.eai.org",
        "description": "Nonprofit resource for video and media art. Distributes and preserves a major collection of artist-made video works.",
        "highlight": "Video art distribution hub",
    },
    {
        "name": "Gotham Film & Media Institute",
        "category": "organization",
        "address": "30 John St, New York, NY 10038",
        "neighborhood": "FiDi",
        "borough": "Manhattan",
        "lat": 40.7088,
        "lng": -74.0060,
        "url": "https://gotham.pro",
        "description": "Formerly IFP. Nonprofit supporting independent filmmakers through labs, fiscal sponsorship, and the Gotham Awards.",
        "highlight": "Gotham Awards + filmmaker labs",
    },
    {
        "name": "New York Women in Film & TV",
        "category": "organization",
        "address": "6 E 39th St, New York, NY 10016",
        "neighborhood": "Midtown",
        "borough": "Manhattan",
        "lat": 40.7515,
        "lng": -73.9812,
        "url": "https://www.nywift.org",
        "description": "Nonprofit supporting women and gender-nonconforming professionals in film, TV, and digital media through networking, panels, and grants.",
        "highlight": "Women in film advocacy",
    },
    {
        "name": "Rooftop Films",
        "category": "organization",
        "address": "232 3rd St, Suite E-106, Brooklyn, NY 11215",
        "neighborhood": "Gowanus",
        "borough": "Brooklyn",
        "lat": 40.6749,
        "lng": -73.9877,
        "url": "https://rooftopfilms.com",
        "description": "A Gowanus-based nonprofit presenting outdoor film screenings across NYC rooftops and unique venues each summer, championing independent and short filmmakers since 1997.",
        "highlight": "Films under the stars",
    },
    {
        "name": "Women Make Movies",
        "category": "organization",
        "address": "231 W 29th St, Suite 1006, New York, NY 10001",
        "neighborhood": "Chelsea",
        "borough": "Manhattan",
        "lat": 40.7483,
        "lng": -73.9938,
        "url": "https://www.wmm.com",
        "description": "The world's largest distributor of films by and about women, providing production assistance, fiscal sponsorship, and distribution for women filmmakers for over 45 years.",
        "highlight": "Amplifying women's voices",
    },
    {
        "name": "Reel Works",
        "category": "organization",
        "address": "540 President St, Brooklyn, NY 11215",
        "neighborhood": "Gowanus",
        "borough": "Brooklyn",
        "lat": 40.6773,
        "lng": -73.9851,
        "url": "https://www.reelworks.org",
        "description": "An Emmy-winning Gowanus nonprofit pairing teens with professional filmmaker mentors to create original media, with a workforce development program for media careers.",
        "highlight": "Youth filmmaking launchpad",
    },
    {
        "name": "New York Film Academy",
        "category": "organization",
        "address": "17 Battery Pl, New York, NY 10004",
        "neighborhood": "Battery Park",
        "borough": "Manhattan",
        "lat": 40.7049,
        "lng": -74.0163,
        "url": "https://www.nyfa.edu",
        "description": "A hands-on film and performing arts school at Battery Park offering accelerated programs in filmmaking, acting, screenwriting, and more with professional-grade facilities.",
        "highlight": "Learn filmmaking by doing",
    },
    # ── Schools (10) ──
    {
        "name": "Millennium Film Workshop",
        "category": "school",
        "address": "167 Wilson Ave, Brooklyn, NY 11237",
        "neighborhood": "Bushwick",
        "borough": "Brooklyn",
        "lat": 40.6982,
        "lng": -73.9234,
        "url": "https://millenniumfilm.org",
        "description": "Historic artist-run center for experimental film. Offers equipment access, screening space, and filmmaking workshops.",
        "highlight": "Historic experimental film center",
    },
    {
        "name": "NYU Tisch School of the Arts",
        "category": "school",
        "address": "721 Broadway, New York, NY 10003",
        "neighborhood": "Greenwich Village",
        "borough": "Manhattan",
        "lat": 40.7290,
        "lng": -73.9938,
        "url": "https://tisch.nyu.edu",
        "description": "NYU's film school hosts public screenings, visiting artist talks, and occasional open workshops on experimental filmmaking.",
        "highlight": "Public screenings + talks",
    },
    {
        "name": "DCTV",
        "category": "school",
        "address": "87 Lafayette St, New York, NY 10013",
        "neighborhood": "Chinatown",
        "borough": "Manhattan",
        "lat": 40.7178,
        "lng": -73.9999,
        "url": "https://dctvny.org",
        "description": "Downtown Community Television Center. Nonprofit media center offering production classes, equipment rental, and screening space.",
        "highlight": "Community media center",
    },
    {
        "name": "UnionDocs",
        "category": "school",
        "address": "322 Union Ave, Brooklyn, NY 11211",
        "neighborhood": "Williamsburg",
        "borough": "Brooklyn",
        "lat": 40.7063,
        "lng": -73.9510,
        "url": "https://uniondocs.org",
        "description": "Center for documentary art. Offers collaborative programs, artist residencies, workshops, and a regular screening series.",
        "highlight": "Documentary art center",
    },
    {
        "name": "SVA (School of Visual Arts)",
        "category": "school",
        "address": "209 E 23rd St, New York, NY 10010",
        "neighborhood": "Gramercy",
        "borough": "Manhattan",
        "lat": 40.7388,
        "lng": -73.9825,
        "url": "https://sva.edu",
        "description": "Art and design college with BFA/MFA programs in film and animation. Hosts public screenings, visiting artist events, and open workshops.",
        "highlight": "Film + animation programs",
    },
    {
        "name": "Manhattan Edit Workshop",
        "category": "school",
        "address": "119 W 23rd St, Suite 1000, New York, NY 10011",
        "neighborhood": "Flatiron",
        "borough": "Manhattan",
        "lat": 40.7432,
        "lng": -73.9933,
        "url": "https://www.mewshop.com",
        "description": "A Flatiron-based post-production training center offering professional courses in Avid, Premiere, After Effects, and DaVinci Resolve, serving editors for over 20 years.",
        "highlight": "Master the edit",
    },
    {
        "name": "The Color House",
        "category": "school",
        "address": "177 Lafayette St, New York, NY 10013",
        "neighborhood": "SoHo",
        "borough": "Manhattan",
        "lat": 40.7205,
        "lng": -73.9986,
        "url": "http://thecolorhouseny.com",
        "description": "A SoHo full-service photo lab and color grading facility providing C-41/E-6/B&W processing, drum scanning, fine-art printing, and digital imaging.",
        "highlight": "Color done right",
    },
    {
        "name": "Pink Folder Film House",
        "category": "school",
        "address": "1113 Fulton St, Brooklyn, NY 11238",
        "neighborhood": "Greenpoint",
        "borough": "Brooklyn",
        "lat": 40.6815,
        "lng": -73.9571,
        "url": "https://www.pinkfolderfilmhouse.com",
        "description": "An analog photo lab and darkroom offering film developing, scanning, printing, and intimate small-group workshops to nurture emerging photographers.",
        "highlight": "Analog lab with soul",
    },
    {
        "name": "Columbia University Film",
        "category": "school",
        "address": "2960 Broadway, New York, NY 10027",
        "neighborhood": "Morningside Heights",
        "borough": "Manhattan",
        "lat": 40.8085,
        "lng": -73.9635,
        "url": "https://arts.columbia.edu/film",
        "description": "Columbia's MFA Film program is one of the top film schools in the country, known for producing Oscar-winning filmmakers in a rigorous conservatory setting.",
        "highlight": "Ivy League filmmaking",
    },
    {
        "name": "Pratt Institute Film",
        "category": "school",
        "address": "200 Willoughby Ave, Brooklyn, NY 11205",
        "neighborhood": "Clinton Hill",
        "borough": "Brooklyn",
        "lat": 40.6922,
        "lng": -73.9627,
        "url": "https://www.pratt.edu",
        "description": "Pratt's Film and Video Department in Clinton Hill features dedicated production and education space at the northeast corner of their historic Brooklyn campus.",
        "highlight": "Art school film vision",
    },
    # ── Additional Cinemas / Theaters (6) ──
    {
        "name": "Village East by Angelika",
        "category": "cinema",
        "address": "181-189 2nd Ave, New York, NY 10003",
        "neighborhood": "East Village",
        "borough": "Manhattan",
        "lat": 40.7310,
        "lng": -73.9872,
        "url": "https://angelikafilmcenter.com/villageeast",
        "description": "A seven-screen arthouse cinema housed in a landmarked 1926 Yiddish theater, featuring a spectacular Moorish Revival auditorium alongside indie and mainstream programming.",
        "highlight": "Yiddish theater turned cinema",
    },
    {
        "name": "SVA Theatre",
        "category": "cinema",
        "address": "333 W 23rd St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough": "Manhattan",
        "lat": 40.7456,
        "lng": -73.9992,
        "url": "https://www.sva.edu/events/sva-theatre",
        "description": "A 480-seat state-of-the-art theater operated by the School of Visual Arts, hosting indie premieres, Q&As, and film festival screenings open to the public.",
        "highlight": "Major indie premiere venue",
    },
    {
        "name": "Cinépolis Chelsea",
        "category": "cinema",
        "address": "260 W 23rd St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough": "Manhattan",
        "lat": 40.7453,
        "lng": -73.9978,
        "url": "https://cinepolisusa.com/chelsea",
        "description": "A luxury arthouse cinema in Chelsea with recliner seating, full bar, and a curated mix of independent, foreign, and mainstream films.",
        "highlight": "Luxury arthouse experience",
    },
    {
        "name": "Kew Gardens Cinemas",
        "category": "cinema",
        "address": "81-05 Lefferts Blvd, Kew Gardens, NY 11415",
        "neighborhood": "Kew Gardens",
        "borough": "Queens",
        "lat": 40.7053,
        "lng": -73.8306,
        "url": "https://kewgardenscinema.com",
        "description": "A beloved neighborhood cinema operating since 1938, one of Queens' last independent movie houses, showing indie, foreign, and select mainstream films.",
        "highlight": "Queens neighborhood gem since '38",
    },
    {
        "name": "Regal Essex Crossing",
        "category": "cinema",
        "address": "129 Delancey St, New York, NY 10002",
        "neighborhood": "Lower East Side",
        "borough": "Manhattan",
        "lat": 40.7183,
        "lng": -73.9883,
        "url": "https://www.regmovies.com/theatres/regal-essex-crossing",
        "description": "A modern 14-screen multiplex in the Essex Crossing development on the Lower East Side, featuring IMAX, RPX, and ScreenX alongside indie and arthouse programming.",
        "highlight": "Modern LES multiplex",
    },
    {
        "name": "FIAF — CinéSalon",
        "category": "cinema",
        "address": "22 E 60th St, New York, NY 10022",
        "neighborhood": "Upper East Side",
        "borough": "Manhattan",
        "lat": 40.7640,
        "lng": -73.9693,
        "url": "https://fiaf.org/cinesalon",
        "description": "The French Institute Alliance Française presents CinéSalon, a curated French and Francophone film screening series with filmmaker discussions in an intimate setting.",
        "highlight": "French cinema on the UES",
    },
    # ── Additional Museums / Galleries with Film Programs (7) ──
    {
        "name": "Solomon R. Guggenheim Museum",
        "category": "museum",
        "address": "1071 5th Ave, New York, NY 10128",
        "neighborhood": "Upper East Side",
        "borough": "Manhattan",
        "lat": 40.7830,
        "lng": -73.9590,
        "url": "https://www.guggenheim.org",
        "description": "Frank Lloyd Wright's iconic spiral museum presents film and video art exhibitions, moving image installations, and occasional screening programs.",
        "highlight": "Film/video art in Wright's spiral",
    },
    {
        "name": "The Kitchen",
        "category": "museum",
        "address": "512 W 19th St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough": "Manhattan",
        "lat": 40.7441,
        "lng": -74.0046,
        "url": "https://thekitchen.org",
        "description": "A legendary nonprofit space for video, music, dance, performance, and film since 1971. Pioneered video art exhibitions and continues championing emerging artists.",
        "highlight": "Video art pioneer since '71",
    },
    {
        "name": "The Shed",
        "category": "museum",
        "address": "545 W 30th St, New York, NY 10001",
        "neighborhood": "Hudson Yards",
        "borough": "Manhattan",
        "lat": 40.7534,
        "lng": -74.0027,
        "url": "https://theshed.org",
        "description": "A major arts center at Hudson Yards with a telescoping outer shell, commissioning and presenting original works across all disciplines including film, video, and immersive media.",
        "highlight": "Next-gen arts + film commissions",
    },
    {
        "name": "Swiss Institute",
        "category": "museum",
        "address": "38 St Marks Pl, New York, NY 10003",
        "neighborhood": "East Village",
        "borough": "Manhattan",
        "lat": 40.7282,
        "lng": -73.9893,
        "url": "https://www.swissinstitute.net",
        "description": "A contemporary art space presenting exhibitions, performances, and film programs that connect Swiss and international artistic practices.",
        "highlight": "Contemporary art + film programs",
    },
    {
        "name": "e-flux Screening Room",
        "category": "museum",
        "address": "172 Classon Ave, Brooklyn, NY 11205",
        "neighborhood": "Clinton Hill",
        "borough": "Brooklyn",
        "lat": 40.6868,
        "lng": -73.9601,
        "url": "https://www.e-flux.com/screeningroom",
        "description": "An art space and screening room operated by the influential e-flux platform, presenting regular film screenings, artist talks, and moving image exhibitions.",
        "highlight": "Art world film screenings",
    },
    {
        "name": "SculptureCenter",
        "category": "museum",
        "address": "44-19 Purves St, Long Island City, NY 11101",
        "neighborhood": "Long Island City",
        "borough": "Queens",
        "lat": 40.7470,
        "lng": -73.9420,
        "url": "https://www.sculpture-center.org",
        "description": "A contemporary art museum in a former trolley repair shop, exhibiting sculpture and moving image work that expands the definition of three-dimensional art.",
        "highlight": "Video art in a trolley shop",
    },
    {
        "name": "The Studio Museum in Harlem",
        "category": "museum",
        "address": "429 W 127th St, New York, NY 10027",
        "neighborhood": "Harlem",
        "borough": "Manhattan",
        "lat": 40.8106,
        "lng": -73.9537,
        "url": "https://www.studiomuseum.org",
        "description": "The leading museum devoted to visual art by people of African descent, presenting exhibitions that frequently include film, video, and moving image work by Black artists.",
        "highlight": "Black artists + moving image",
    },
    # ── Cultural Institutions with Screening Programs (7) ──
    {
        "name": "Japan Society",
        "category": "cinema",
        "address": "333 E 47th St, New York, NY 10017",
        "neighborhood": "Midtown East",
        "borough": "Manhattan",
        "lat": 40.7527,
        "lng": -73.9680,
        "url": "https://www.japansociety.org",
        "description": "A premier cultural institution presenting the best of Japanese cinema through curated film series, premieres, and filmmaker Q&As in a purpose-built theater.",
        "highlight": "Premier Japanese cinema series",
    },
    {
        "name": "Asia Society",
        "category": "cinema",
        "address": "725 Park Ave, New York, NY 10021",
        "neighborhood": "Upper East Side",
        "borough": "Manhattan",
        "lat": 40.7693,
        "lng": -73.9644,
        "url": "https://asiasociety.org",
        "description": "A leading cultural institution presenting Asian and Asian American cinema through regular screening series, filmmaker conversations, and curated film festivals.",
        "highlight": "Asian cinema screenings",
    },
    {
        "name": "92NY (92nd Street Y)",
        "category": "cinema",
        "address": "1395 Lexington Ave, New York, NY 10128",
        "neighborhood": "Upper East Side",
        "borough": "Manhattan",
        "lat": 40.7848,
        "lng": -73.9533,
        "url": "https://www.92ny.org",
        "description": "A storied Upper East Side cultural center hosting regular film series, documentary premieres, and in-depth filmmaker conversations in its historic auditorium.",
        "highlight": "Film series + filmmaker talks",
    },
    {
        "name": "Instituto Cervantes New York",
        "category": "cinema",
        "address": "211 E 49th St, New York, NY 10017",
        "neighborhood": "Midtown East",
        "borough": "Manhattan",
        "lat": 40.7547,
        "lng": -73.9714,
        "url": "https://nyork.cervantes.es",
        "description": "Spain's official cultural center in NYC, presenting Spanish and Latin American cinema through regular screening series, festivals, and filmmaker events.",
        "highlight": "Spanish-language cinema",
    },
    {
        "name": "Scandinavia House",
        "category": "cinema",
        "address": "58 Park Ave, New York, NY 10016",
        "neighborhood": "Midtown East",
        "borough": "Manhattan",
        "lat": 40.7488,
        "lng": -73.9788,
        "url": "https://www.scandinaviahouse.org",
        "description": "The Nordic Center in America, presenting Scandinavian cinema through curated film series showcasing the best of Danish, Finnish, Icelandic, Norwegian, and Swedish film.",
        "highlight": "Nordic cinema screenings",
    },
    {
        "name": "The Greene Space (WNYC)",
        "category": "organization",
        "address": "44 Charlton St, New York, NY 10014",
        "neighborhood": "SoHo",
        "borough": "Manhattan",
        "lat": 40.7269,
        "lng": -74.0061,
        "url": "https://www.thegreenespace.org",
        "description": "WNYC's intimate performance and event space hosting documentary screenings, film-related conversations, live media events, and podcast tapings.",
        "highlight": "Film events + live media",
    },
    {
        "name": "Tribeca Film Center",
        "category": "organization",
        "address": "375 Greenwich St, New York, NY 10013",
        "neighborhood": "Tribeca",
        "borough": "Manhattan",
        "lat": 40.7204,
        "lng": -74.0104,
        "url": "https://www.tribecafilm.com",
        "description": "Co-founded by Robert De Niro, the Tribeca Film Center houses industry screening rooms, production offices, and serves as the hub for the Tribeca Film Festival.",
        "highlight": "Industry hub + Tribeca Festival HQ",
    },
]


def seed():
    """Create tables and insert seed venues."""
    conn = db.init_db()
    # Clear existing data
    conn.execute("DELETE FROM venues")
    for v in VENUES:
        conn.execute(
            """INSERT INTO venues (name, category, address, neighborhood, borough,
                                   lat, lng, url, description, highlight, status)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active')""",
            (
                v["name"],
                v["category"],
                v.get("address"),
                v.get("neighborhood"),
                v.get("borough"),
                v["lat"],
                v["lng"],
                v.get("url"),
                v.get("description"),
                v.get("highlight"),
            ),
        )
    conn.commit()
    count = conn.execute("SELECT COUNT(*) FROM venues").fetchone()[0]
    print(f"Seeded {count} venues.")
    conn.close()


if __name__ == "__main__":
    seed()
