"""Seed the festival tracker database with curated experimental film festivals."""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

import db

FESTIVALS = [
    {
        "name": "Ann Arbor Film Festival",
        "city": "Ann Arbor, MI",
        "country": "USA",
        "website": "https://www.aafilmfest.org",
        "filmfreeway": "https://filmfreeway.com/AnnArborFilmFestival",
        "description": "The oldest avant-garde and experimental film festival in North America, running since 1963.",
        "focus": "experimental",
        "tier": "major",
        "event_month": "March",
        "premiere_req": "none",
        "prestige": 5,
        "acceptance": "selective",
        "known_for": "Oldest avant-garde festival in North America",
        "deadlines": [
            {"year": 2025, "tier": "early", "deadline": "2024-09-15", "fee_usd": 35.0},
            {"year": 2025, "tier": "regular", "deadline": "2024-11-01", "fee_usd": 50.0},
            {"year": 2025, "tier": "late", "deadline": "2025-01-05", "fee_usd": 65.0},
            {"year": 2026, "tier": "early", "deadline": "2025-09-15", "fee_usd": 40.0},
            {"year": 2026, "tier": "regular", "deadline": "2025-11-01", "fee_usd": 55.0},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 40},
            {"name": "animation", "max_runtime": 30},
            {"name": "music video", "max_runtime": 15},
        ],
    },
    {
        "name": "International Film Festival Rotterdam (IFFR)",
        "city": "Rotterdam",
        "country": "Netherlands",
        "website": "https://iffr.com",
        "filmfreeway": None,
        "description": "One of the largest audience-driven film festivals in the world, known for championing independent and experimental cinema.",
        "focus": "experimental",
        "tier": "major",
        "event_month": "January-February",
        "premiere_req": "international",
        "prestige": 5,
        "acceptance": "very selective",
        "known_for": "Championing independent cinema since 1972",
        "deadlines": [
            {"year": 2026, "tier": "regular", "deadline": "2025-09-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 60},
            {"name": "feature film", "min_runtime": 60},
            {"name": "mid-length", "min_runtime": 30, "max_runtime": 60},
        ],
    },
    {
        "name": "FIDMarseille",
        "city": "Marseille",
        "country": "France",
        "website": "https://fidmarseille.org",
        "filmfreeway": None,
        "description": "International cinema festival focused on documentary, fiction, and experimental work that pushes boundaries.",
        "focus": "experimental",
        "tier": "major",
        "event_month": "June",
        "premiere_req": "international",
        "prestige": 5,
        "acceptance": "very selective",
        "known_for": "Boundary-dissolving documentary and fiction hybrids",
        "deadlines": [
            {"year": 2026, "tier": "regular", "deadline": "2026-02-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 60},
            {"name": "feature film", "min_runtime": 60},
        ],
    },
    {
        "name": "New York Film Festival — Projections",
        "city": "New York, NY",
        "country": "USA",
        "website": "https://www.filmlinc.org/nyff/projections/",
        "filmfreeway": None,
        "description": "NYFF's dedicated sidebar for avant-garde and experimental moving image work.",
        "focus": "avant-garde",
        "tier": "major",
        "event_month": "September-October",
        "premiere_req": "north_american",
        "prestige": 5,
        "acceptance": "very selective",
        "known_for": "Premier avant-garde sidebar at NYFF",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-05-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-05-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 45},
            {"name": "experimental feature", "min_runtime": 45},
        ],
    },
    {
        "name": "Toronto International Film Festival — Wavelengths",
        "city": "Toronto",
        "country": "Canada",
        "website": "https://www.tiff.net",
        "filmfreeway": None,
        "description": "TIFF's programme for avant-garde cinema, named after Michael Snow's landmark 1967 film.",
        "focus": "avant-garde",
        "tier": "major",
        "event_month": "September",
        "premiere_req": "world",
        "prestige": 5,
        "acceptance": "very selective",
        "known_for": "Named after Michael Snow's landmark film",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-04-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-04-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 50},
            {"name": "feature film", "min_runtime": 50},
        ],
    },
    {
        "name": "FRACTO",
        "city": "Berlin",
        "country": "Germany",
        "website": "https://www.fracto.org",
        "filmfreeway": "https://filmfreeway.com/FRACTO",
        "description": "Berlin-based experimental film encounter dedicated to artist-run film culture and the materiality of cinema.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "November",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Artist-run film culture and materiality",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-07-31", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-07-31", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 30},
            {"name": "expanded cinema"},
        ],
    },
    {
        "name": "Lausanne Underground Film & Music Festival",
        "city": "Lausanne",
        "country": "Switzerland",
        "website": "https://www.lfrancais.ch",
        "filmfreeway": "https://filmfreeway.com/LUFF",
        "description": "Festival celebrating underground, experimental, and outsider film alongside extreme and avant-garde music.",
        "focus": "underground",
        "tier": "mid",
        "event_month": "October",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Underground film meets avant-garde music",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-06-30", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-06-30", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "feature film", "min_runtime": 40},
            {"name": "music video", "max_runtime": 15},
        ],
    },
    {
        "name": "Videoex",
        "city": "Zurich",
        "country": "Switzerland",
        "website": "https://www.videoex.ch",
        "filmfreeway": "https://filmfreeway.com/Videoex",
        "description": "International festival for experimental film and video art in Zurich.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "May-June",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Swiss hub for video art experimentation",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-01-31", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-01-31", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 30},
            {"name": "video art"},
        ],
    },
    {
        "name": "Onion City Experimental Film Festival",
        "city": "Chicago, IL",
        "country": "USA",
        "website": "https://www.chicagofilmmakers.org/onion-city",
        "filmfreeway": "https://filmfreeway.com/OnionCity",
        "description": "Chicago's premier experimental film festival, presented by Chicago Filmmakers.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "June",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Chicago's grassroots experimental film community",
        "deadlines": [
            {"year": 2025, "tier": "early", "deadline": "2025-01-15", "fee_usd": 15.0},
            {"year": 2025, "tier": "regular", "deadline": "2025-03-01", "fee_usd": 25.0},
            {"year": 2025, "tier": "late", "deadline": "2025-04-01", "fee_usd": 35.0},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 40},
            {"name": "animation", "max_runtime": 15},
        ],
    },
    {
        "name": "VAEFF — Video Art & Experimental Film Festival",
        "city": "New York, NY",
        "country": "USA",
        "website": "https://www.vaeff.org",
        "filmfreeway": "https://filmfreeway.com/VAEFF",
        "description": "New York-based festival showcasing video art and experimental film from around the world.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "November",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Bridging video art and experimental cinema",
        "deadlines": [
            {"year": 2025, "tier": "early", "deadline": "2025-04-15", "fee_usd": 15.0},
            {"year": 2025, "tier": "regular", "deadline": "2025-06-15", "fee_usd": 25.0},
            {"year": 2025, "tier": "late", "deadline": "2025-08-15", "fee_usd": 35.0},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 20},
            {"name": "video art", "max_runtime": 20},
            {"name": "experimental feature", "min_runtime": 40},
        ],
    },
    {
        "name": "Bucharest International Experimental Film Festival",
        "city": "Bucharest",
        "country": "Romania",
        "website": "https://www.bieff.ro",
        "filmfreeway": "https://filmfreeway.com/BIEFF",
        "description": "Romania's leading experimental film festival, championing innovative visual language.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "November",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Eastern Europe's experimental cinema beacon",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-07-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-07-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 30},
        ],
    },
    {
        "name": "ARKIPEL Jakarta",
        "city": "Jakarta",
        "country": "Indonesia",
        "website": "https://arkipel.org",
        "filmfreeway": None,
        "description": "Jakarta international documentary and experimental film festival exploring the boundaries of cinema.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "August",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Southeast Asian experimental documentary platform",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-04-30", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-04-30", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "feature film", "min_runtime": 50},
        ],
    },
    {
        "name": "Bogotá Experimental Film Festival (CineAutopsia)",
        "city": "Bogotá",
        "country": "Colombia",
        "website": "https://www.cineautopsia.com",
        "filmfreeway": "https://filmfreeway.com/CineAutopsia",
        "description": "Colombia's experimental film festival celebrating radical and non-narrative cinema.",
        "focus": "experimental",
        "tier": "emerging",
        "event_month": "October",
        "premiere_req": "none",
        "prestige": 2,
        "acceptance": "moderate",
        "known_for": "Latin American radical non-narrative cinema",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-06-30", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-06-30", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 40},
            {"name": "video art", "max_runtime": 15},
        ],
    },
    {
        "name": "Experiments in Cinema",
        "city": "Albuquerque, NM",
        "country": "USA",
        "website": "https://www.experimentsincinema.org",
        "filmfreeway": "https://filmfreeway.com/ExperimentsInCinema",
        "description": "Albuquerque-based festival devoted to experimental, avant-garde, and no-budget cinema.",
        "focus": "experimental",
        "tier": "emerging",
        "event_month": "April",
        "premiere_req": "none",
        "prestige": 2,
        "acceptance": "open",
        "known_for": "Welcoming no-budget and first-time experimentalists",
        "deadlines": [
            {"year": 2025, "tier": "early", "deadline": "2024-10-01", "fee_usd": 10.0},
            {"year": 2025, "tier": "regular", "deadline": "2024-12-01", "fee_usd": 20.0},
            {"year": 2025, "tier": "late", "deadline": "2025-01-15", "fee_usd": 30.0},
            {"year": 2026, "tier": "early", "deadline": "2025-10-01", "fee_usd": 10.0},
            {"year": 2026, "tier": "regular", "deadline": "2025-12-01", "fee_usd": 20.0},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 40},
            {"name": "animation", "max_runtime": 20},
            {"name": "music video", "max_runtime": 10},
        ],
    },
    {
        "name": "Paris Festival for Different and Experimental Cinema",
        "city": "Paris",
        "country": "France",
        "website": "https://cjcinema.org",
        "filmfreeway": None,
        "description": "Long-running Parisian festival organized by Collectif Jeune Cinéma, France's oldest artist-run film cooperative.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "October",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "France's oldest artist-run film cooperative",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-05-31", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-05-31", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 30},
            {"name": "expanded cinema"},
        ],
    },
    {
        "name": "Oberhausen International Short Film Festival",
        "city": "Oberhausen",
        "country": "Germany",
        "website": "https://www.kurzfilmtage.de",
        "filmfreeway": None,
        "description": "One of the oldest and most important short film festivals in the world, with a strong tradition of showcasing experimental and avant-garde work since 1954.",
        "focus": "experimental",
        "tier": "major",
        "event_month": "May",
        "premiere_req": "none",
        "prestige": 5,
        "acceptance": "selective",
        "known_for": "Birthplace of New German Cinema movement",
        "deadlines": [
            {"year": 2026, "tier": "regular", "deadline": "2026-01-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "international competition", "max_runtime": 35},
            {"name": "german competition", "max_runtime": 35},
            {"name": "muvideos", "max_runtime": 15},
        ],
    },
    {
        "name": "Viennale",
        "city": "Vienna",
        "country": "Austria",
        "website": "https://www.viennale.at",
        "filmfreeway": None,
        "description": "Austria's most important international film event, known for curating adventurous and formally ambitious cinema.",
        "focus": "avant-garde",
        "tier": "major",
        "event_month": "October",
        "premiere_req": "none",
        "prestige": 4,
        "acceptance": "very selective",
        "known_for": "Austria's flagship for adventurous cinema",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-06-30", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-06-30", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 45},
            {"name": "feature film", "min_runtime": 45},
        ],
    },
    {
        "name": "Images Festival",
        "city": "Toronto",
        "country": "Canada",
        "website": "https://imagesfestival.com",
        "filmfreeway": "https://filmfreeway.com/ImagesFestival",
        "description": "North America's longest-running festival for experimental and independent moving image culture, spanning film, video, performance, and installation.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "April",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Longest-running moving image festival in North America",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2024-11-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2025-11-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 45},
            {"name": "feature film", "min_runtime": 45},
            {"name": "installation"},
            {"name": "live performance"},
        ],
    },
    {
        "name": "Edinburgh International Film Festival",
        "city": "Edinburgh",
        "country": "UK",
        "website": "https://www.edfilmfest.org.uk",
        "filmfreeway": None,
        "description": "The world's oldest continually running film festival, with dedicated strands for experimental and artist-moving-image work.",
        "focus": "experimental",
        "tier": "major",
        "event_month": "August",
        "premiere_req": "international",
        "prestige": 4,
        "acceptance": "selective",
        "known_for": "World's oldest continually running film festival",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-03-31", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-03-31", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 40},
            {"name": "feature film", "min_runtime": 40},
        ],
    },
    {
        "name": "S8 Mostra de Cinema Periférico",
        "city": "A Coruña",
        "country": "Spain",
        "website": "https://s8cinema.com",
        "filmfreeway": None,
        "description": "Spanish festival dedicated to peripheral cinema, analog film, and expanded practices rooted in materiality and process.",
        "focus": "avant-garde",
        "tier": "mid",
        "event_month": "June",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Analog film and peripheral cinema practices",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-02-28", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-02-28", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "feature film", "min_runtime": 30},
            {"name": "expanded cinema"},
            {"name": "live performance"},
        ],
    },
    {
        "name": "25 FPS Festival",
        "city": "Zagreb",
        "country": "Croatia",
        "website": "https://www.25fps.hr",
        "filmfreeway": "https://filmfreeway.com/25FPS",
        "description": "International festival of experimental film and video in Zagreb, exploring the margins between cinema, visual arts, and new media.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "September",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Cinema-visual arts crossover in the Balkans",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-06-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-06-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 30},
            {"name": "video art"},
        ],
    },
    {
        "name": "Antimatter [Media Art]",
        "city": "Victoria, BC",
        "country": "Canada",
        "website": "https://www.antimatter.ca",
        "filmfreeway": "https://filmfreeway.com/AntimatterMediaArt",
        "description": "Festival of film, video, and new media art on Canada's west coast, championing non-mainstream and artist-driven work.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "October",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "West coast Canadian media art gathering",
        "deadlines": [
            {"year": 2025, "tier": "early", "deadline": "2025-04-01", "fee_usd": 15.0},
            {"year": 2025, "tier": "regular", "deadline": "2025-06-01", "fee_usd": 25.0},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "feature film", "min_runtime": 30},
            {"name": "media art"},
        ],
    },
    {
        "name": "Curtocircuito International Film Festival",
        "city": "Santiago de Compostela",
        "country": "Spain",
        "website": "https://curtocircuito.org",
        "filmfreeway": "https://filmfreeway.com/Curtocircuito",
        "description": "Spanish short film festival with a strong experimental program, bridging cinema and contemporary art.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "October",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Short film bridging cinema and contemporary art",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-06-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-06-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "experimental short", "max_runtime": 30},
        ],
    },
    {
        "name": "Crossroads (SFMOMA)",
        "city": "San Francisco, CA",
        "country": "USA",
        "website": "https://www.sfmoma.org/series/crossroads/",
        "filmfreeway": None,
        "description": "SFMOMA's annual festival of experimental film and video, curated by the museum's film and media arts department.",
        "focus": "avant-garde",
        "tier": "mid",
        "event_month": "April",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Museum-curated experimental film at SFMOMA",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2024-12-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2025-12-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 30},
        ],
    },
    {
        "name": "Punto de Vista",
        "city": "Pamplona",
        "country": "Spain",
        "website": "https://www.puntodevistafestival.com",
        "filmfreeway": None,
        "description": "International documentary and experimental film festival in Navarra, exploring non-fiction cinema at its most adventurous.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "February-March",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Adventurous non-fiction at cinema's edge",
        "deadlines": [
            {"year": 2026, "tier": "regular", "deadline": "2025-10-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 60},
            {"name": "feature film", "min_runtime": 60},
        ],
    },
    {
        "name": "Alchemy Film and Moving Image Festival",
        "city": "Hawick",
        "country": "UK",
        "website": "https://alchemyfilmfestival.org.uk",
        "filmfreeway": "https://filmfreeway.com/AlchemyFilmandMovingImageFestival",
        "description": "Scottish Borders festival celebrating experimental film and artists' moving image in an intimate small-town setting.",
        "focus": "experimental",
        "tier": "emerging",
        "event_month": "May",
        "premiere_req": "none",
        "prestige": 2,
        "acceptance": "moderate",
        "known_for": "Intimate small-town experimental film gathering",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2024-12-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2025-12-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "feature film", "min_runtime": 30},
            {"name": "installation"},
        ],
    },
    {
        "name": "EMAF (European Media Art Festival)",
        "city": "Osnabrück",
        "country": "Germany",
        "website": "https://www.emaf.de",
        "filmfreeway": "https://filmfreeway.com/EMAF",
        "description": "One of the most significant forums for international media art, experimental film, and digital culture in Europe.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "April",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Europe's leading media art and digital culture forum",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2024-12-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2025-12-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 30},
            {"name": "media art"},
            {"name": "installation"},
        ],
    },
    {
        "name": "Jihlava International Documentary Film Festival",
        "city": "Jihlava",
        "country": "Czech Republic",
        "website": "https://www.ji-hlava.com",
        "filmfreeway": None,
        "description": "Central Europe's largest documentary film festival with a dedicated section for experimental and essay cinema.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "October",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Central Europe's largest documentary festival",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-07-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-07-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 50},
            {"name": "feature film", "min_runtime": 50},
        ],
    },
    {
        "name": "Black Star Film Festival",
        "city": "Philadelphia, PA",
        "country": "USA",
        "website": "https://www.blackstarfest.org",
        "filmfreeway": "https://filmfreeway.com/BlackStar",
        "description": "Festival centering the work of Black, Brown, and Indigenous filmmakers, including experimental and avant-garde shorts and features.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "August",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Centering BIPOC voices in experimental cinema",
        "deadlines": [
            {"year": 2025, "tier": "early", "deadline": "2025-01-15", "fee_usd": 15.0},
            {"year": 2025, "tier": "regular", "deadline": "2025-03-15", "fee_usd": 30.0},
            {"year": 2025, "tier": "late", "deadline": "2025-05-01", "fee_usd": 45.0},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 40},
            {"name": "feature film", "min_runtime": 40},
            {"name": "experimental short", "max_runtime": 20},
            {"name": "music video", "max_runtime": 10},
        ],
    },
    {
        "name": "Berlinale Forum Expanded",
        "city": "Berlin",
        "country": "Germany",
        "website": "https://www.berlinale.de/en/programme/sections/forum-expanded.html",
        "filmfreeway": None,
        "description": "The Berlinale's platform for film and art in the expanded field, presenting installations, performances, and experimental works at the intersection of cinema and visual arts.",
        "focus": "avant-garde",
        "tier": "major",
        "event_month": "February",
        "premiere_req": "world",
        "prestige": 5,
        "acceptance": "very selective",
        "known_for": "Berlinale's expanded cinema and visual arts platform",
        "deadlines": [
            {"year": 2026, "tier": "regular", "deadline": "2025-09-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 45},
            {"name": "feature film", "min_runtime": 45},
            {"name": "installation"},
            {"name": "performance"},
        ],
    },
    {
        "name": "Locarno Film Festival — Pardi di domani",
        "city": "Locarno",
        "country": "Switzerland",
        "website": "https://www.locarnofestival.ch",
        "filmfreeway": None,
        "description": "Locarno's international short film competition, a launchpad for daring and formally inventive cinema from emerging voices worldwide.",
        "focus": "avant-garde",
        "tier": "major",
        "event_month": "August",
        "premiere_req": "international",
        "prestige": 5,
        "acceptance": "very selective",
        "known_for": "Launchpad for daring emerging voices worldwide",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-04-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-04-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 60},
        ],
    },
    {
        "name": "CPH:DOX",
        "city": "Copenhagen",
        "country": "Denmark",
        "website": "https://cphdox.dk",
        "filmfreeway": None,
        "description": "One of the world's largest documentary film festivals, with strong programming in hybrid, essay, and experimental non-fiction.",
        "focus": "experimental",
        "tier": "major",
        "event_month": "March",
        "premiere_req": "international",
        "prestige": 5,
        "acceptance": "very selective",
        "known_for": "World leader in hybrid documentary forms",
        "deadlines": [
            {"year": 2026, "tier": "regular", "deadline": "2025-10-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 60},
            {"name": "feature film", "min_runtime": 60},
        ],
    },
    {
        "name": "Courtisane Festival",
        "city": "Ghent",
        "country": "Belgium",
        "website": "https://www.courtisane.be",
        "filmfreeway": None,
        "description": "Ghent-based festival for film, video, and media art that values materiality, process, and radical approaches to image-making.",
        "focus": "avant-garde",
        "tier": "mid",
        "event_month": "March",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Radical materiality and process-based image-making",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2024-11-30", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2025-11-30", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 45},
            {"name": "feature film", "min_runtime": 45},
        ],
    },
    {
        "name": "Yidff (Yamagata International Documentary Film Festival)",
        "city": "Yamagata",
        "country": "Japan",
        "website": "https://www.yidff.jp",
        "filmfreeway": None,
        "description": "Biennial Japanese documentary festival renowned for politically engaged and formally experimental non-fiction cinema from Asia and beyond.",
        "focus": "experimental",
        "tier": "major",
        "event_month": "October",
        "premiere_req": "none",
        "prestige": 4,
        "acceptance": "selective",
        "known_for": "Asia's foremost politically engaged documentary festival",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-04-30", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 60},
            {"name": "feature film", "min_runtime": 60},
        ],
    },
    {
        "name": "EXiS (Experimental Film & Video Festival in Seoul)",
        "city": "Seoul",
        "country": "South Korea",
        "website": "https://www.ex-is.org",
        "filmfreeway": "https://filmfreeway.com/EXiS",
        "description": "Seoul's international experimental film and video festival, one of Asia's leading platforms for avant-garde moving image.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "August",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Asia's leading avant-garde moving image platform",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-05-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-05-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 30},
            {"name": "expanded cinema"},
        ],
    },
    {
        "name": "Media City Film Festival",
        "city": "Windsor, ON",
        "country": "Canada",
        "website": "https://mediacityfilmfestival.com",
        "filmfreeway": "https://filmfreeway.com/MediaCityFilmFestival",
        "description": "Canadian festival celebrating experimental cinema and media art at the border of the U.S. and Canada.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "June",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Cross-border experimental cinema and media art",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-02-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-02-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "feature film", "min_runtime": 30},
            {"name": "installation"},
        ],
    },
    {
        "name": "New York Underground Film Festival",
        "city": "New York, NY",
        "country": "USA",
        "website": "https://www.nyuff.com",
        "filmfreeway": "https://filmfreeway.com/NYUFF",
        "description": "Festival dedicated to transgressive, underground, and no-budget filmmaking in New York City.",
        "focus": "underground",
        "tier": "emerging",
        "event_month": "March",
        "premiere_req": "none",
        "prestige": 2,
        "acceptance": "open",
        "known_for": "Transgressive and no-budget underground filmmaking",
        "deadlines": [
            {"year": 2025, "tier": "early", "deadline": "2024-10-15", "fee_usd": 15.0},
            {"year": 2025, "tier": "regular", "deadline": "2025-01-01", "fee_usd": 25.0},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "feature film", "min_runtime": 40},
            {"name": "animation", "max_runtime": 15},
            {"name": "music video", "max_runtime": 10},
        ],
    },
    {
        "name": "WNDX Festival of Moving Image",
        "city": "Winnipeg, MB",
        "country": "Canada",
        "website": "https://www.wndx.org",
        "filmfreeway": "https://filmfreeway.com/WNDX",
        "description": "Winnipeg's biennial festival for experimental film and moving image art, highlighting artist-driven and process-based work.",
        "focus": "experimental",
        "tier": "emerging",
        "event_month": "October",
        "premiere_req": "none",
        "prestige": 2,
        "acceptance": "moderate",
        "known_for": "Biennial artist-driven prairie film gathering",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-06-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "feature film", "min_runtime": 30},
            {"name": "installation"},
        ],
    },
    {
        "name": "Festival du Nouveau Cinéma",
        "city": "Montréal",
        "country": "Canada",
        "website": "https://nouveaucinema.ca",
        "filmfreeway": None,
        "description": "Montréal festival dedicated to new trends in cinema and new media, with a strong experimental and digital arts component.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "October",
        "premiere_req": "north_american",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "New cinema trends and digital arts convergence",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-06-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-06-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 40},
            {"name": "feature film", "min_runtime": 40},
            {"name": "new media"},
        ],
    },
    {
        "name": "Los Angeles Filmforum",
        "city": "Los Angeles, CA",
        "country": "USA",
        "website": "https://lafilmforum.org",
        "filmfreeway": None,
        "description": "The oldest screening organization in Los Angeles dedicated exclusively to independent, experimental, and avant-garde cinema.",
        "focus": "avant-garde",
        "tier": "mid",
        "event_month": "Year-round",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "LA's oldest experimental screening organization",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-08-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-08-01", "fee_usd": None},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 30},
            {"name": "experimental feature", "min_runtime": 30},
        ],
    },
    {
        "name": "Vila do Conde International Short Film Festival",
        "city": "Vila do Conde",
        "country": "Portugal",
        "website": "https://www.curtas.pt",
        "filmfreeway": "https://filmfreeway.com/CurtasVilaDoCondeFestival",
        "description": "Portuguese short film festival with a respected experimental section and strong connections to gallery and museum culture.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "July",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Portuguese shorts bridging gallery and cinema",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-03-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-03-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "experimental short", "max_runtime": 30},
        ],
    },
    {
        "name": "Kassel Documentary Film and Video Festival",
        "city": "Kassel",
        "country": "Germany",
        "website": "https://www.filmladen.de/dokfest",
        "filmfreeway": "https://filmfreeway.com/KasselDokfest",
        "description": "German festival for documentary, experimental, and essay film, adjacent to the Documenta art world.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "November",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Documentary and essay film near Documenta",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-07-31", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-07-31", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 45},
            {"name": "feature film", "min_runtime": 45},
            {"name": "installation"},
        ],
    },
    {
        "name": "Tampere Film Festival",
        "city": "Tampere",
        "country": "Finland",
        "website": "https://tamperefilmfestival.fi",
        "filmfreeway": "https://filmfreeway.com/TampereFilmFestival",
        "description": "One of the oldest short film festivals in the world (since 1970), with an international competition that embraces experimental forms.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "March",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "One of the world's oldest short film festivals",
        "deadlines": [
            {"year": 2026, "tier": "early", "deadline": "2025-09-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2025-11-01", "fee_usd": 10.0},
        ],
        "categories": [
            {"name": "international competition", "max_runtime": 30},
            {"name": "national competition", "max_runtime": 30},
            {"name": "animation", "max_runtime": 30},
        ],
    },
    {
        "name": "Doclisboa",
        "city": "Lisbon",
        "country": "Portugal",
        "website": "https://www.doclisboa.org",
        "filmfreeway": None,
        "description": "International documentary and experimental film festival in Lisbon, known for curating risk-taking and hybrid cinema.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "October",
        "premiere_req": "international",
        "prestige": 3,
        "acceptance": "selective",
        "known_for": "Risk-taking hybrid cinema from Lisbon",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-06-30", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-06-30", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 60},
            {"name": "feature film", "min_runtime": 60},
        ],
    },
    {
        "name": "Curta Cinema — Rio de Janeiro Short Film Festival",
        "city": "Rio de Janeiro",
        "country": "Brazil",
        "website": "https://www.curtacinema.com.br",
        "filmfreeway": "https://filmfreeway.com/CurtaCinema",
        "description": "Brazil's leading short film festival with an experimental section spotlighting Latin American and international avant-garde voices.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "November",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Latin American experimental shorts showcase",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-07-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-07-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 25},
            {"name": "experimental short", "max_runtime": 25},
            {"name": "animation", "max_runtime": 15},
        ],
    },
    {
        "name": "EMIFF — Edinburgh Experimental Film Festival",
        "city": "Edinburgh",
        "country": "UK",
        "website": "https://www.emiff.org",
        "filmfreeway": "https://filmfreeway.com/EMIFF",
        "description": "Edinburgh's dedicated experimental film festival, showcasing radical, non-narrative, and formally innovative work.",
        "focus": "experimental",
        "tier": "emerging",
        "event_month": "March",
        "premiere_req": "none",
        "prestige": 1,
        "acceptance": "open",
        "known_for": "Dedicated radical non-narrative showcase in Edinburgh",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2024-12-01", "fee_usd": 10.0},
            {"year": 2026, "tier": "regular", "deadline": "2025-12-01", "fee_usd": 10.0},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 20},
            {"name": "experimental feature", "min_runtime": 20},
            {"name": "video art", "max_runtime": 15},
        ],
    },
    {
        "name": "FLEX Fest — Florida Experimental Film/Video Festival",
        "city": "Gainesville, FL",
        "country": "USA",
        "website": "https://www.flexfest.org",
        "filmfreeway": "https://filmfreeway.com/FLEXFest",
        "description": "Annual festival in Gainesville celebrating experimental film, video art, and expanded cinema practices.",
        "focus": "experimental",
        "tier": "emerging",
        "event_month": "April",
        "premiere_req": "none",
        "prestige": 1,
        "acceptance": "open",
        "known_for": "University-rooted expanded cinema in Florida",
        "deadlines": [
            {"year": 2025, "tier": "early", "deadline": "2024-11-01", "fee_usd": 10.0},
            {"year": 2025, "tier": "regular", "deadline": "2025-01-15", "fee_usd": 20.0},
        ],
        "categories": [
            {"name": "experimental short", "max_runtime": 20},
            {"name": "experimental feature", "min_runtime": 20},
            {"name": "expanded cinema"},
        ],
    },
    {
        "name": "L'Alternativa — Barcelona Independent Film Festival",
        "city": "Barcelona",
        "country": "Spain",
        "website": "https://alternativa.cccb.org",
        "filmfreeway": None,
        "description": "Barcelona's festival for independent and non-commercial cinema, hosted at the CCCB cultural center, with a strong experimental program.",
        "focus": "experimental",
        "tier": "mid",
        "event_month": "November",
        "premiere_req": "none",
        "prestige": 3,
        "acceptance": "moderate",
        "known_for": "Independent cinema at Barcelona's CCCB cultural center",
        "deadlines": [
            {"year": 2025, "tier": "regular", "deadline": "2025-07-15", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2026-07-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 30},
            {"name": "feature film", "min_runtime": 30},
        ],
    },
    {
        "name": "Clermont-Ferrand International Short Film Festival",
        "city": "Clermont-Ferrand",
        "country": "France",
        "website": "https://clermont-filmfest.org",
        "filmfreeway": "https://filmfreeway.com/ClermontFerrand",
        "description": "The world's largest short film festival, with a dedicated experimental competition known as Lab Competition alongside its international and national programs.",
        "focus": "experimental",
        "tier": "major",
        "event_month": "January-February",
        "premiere_req": "none",
        "prestige": 5,
        "acceptance": "very selective",
        "known_for": "World's largest short film festival with Lab section",
        "deadlines": [
            {"year": 2026, "tier": "early", "deadline": "2025-06-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2025-09-01", "fee_usd": 25.0},
            {"year": 2026, "tier": "late", "deadline": "2025-10-15", "fee_usd": 45.0},
        ],
        "categories": [
            {"name": "international competition", "max_runtime": 40},
            {"name": "lab competition", "max_runtime": 40},
            {"name": "national competition", "max_runtime": 60},
        ],
    },
    {
        "name": "Sundance Film Festival — New Frontier",
        "city": "Park City, UT",
        "country": "USA",
        "website": "https://www.sundance.org/festivals/sundance-film-festival",
        "filmfreeway": None,
        "description": "Sundance's dedicated section for experimental, immersive, and cross-platform work including VR, XR, AI art, and expanded cinema at the intersection of film, art, and technology.",
        "focus": "experimental",
        "tier": "major",
        "event_month": "January",
        "premiere_req": "world",
        "prestige": 5,
        "acceptance": "very selective",
        "known_for": "Immersive and new media art at Sundance",
        "deadlines": [
            {"year": 2026, "tier": "early", "deadline": "2025-08-01", "fee_usd": None},
            {"year": 2026, "tier": "regular", "deadline": "2025-09-15", "fee_usd": None},
        ],
        "categories": [
            {"name": "short film", "max_runtime": 50},
            {"name": "feature film", "min_runtime": 50},
            {"name": "new media"},
            {"name": "installation"},
        ],
    },
]


def seed(db_path=None):
    """Seed the database with curated festival data."""
    conn = db.init_db(db_path)

    festival_count = 0
    deadline_count = 0
    category_count = 0

    for entry in FESTIVALS:
        # Separate relational data from festival fields
        deadlines = entry.pop("deadlines", [])
        categories = entry.pop("categories", [])

        fid = db.upsert_festival(conn, entry)
        festival_count += 1

        for dl in deadlines:
            conn.execute(
                "INSERT OR IGNORE INTO deadlines (festival_id, year, tier, deadline, fee_usd) "
                "VALUES (?, ?, ?, ?, ?)",
                (fid, dl["year"], dl["tier"], dl["deadline"], dl.get("fee_usd")),
            )
            deadline_count += 1

        for cat in categories:
            conn.execute(
                "INSERT OR IGNORE INTO categories (festival_id, name, min_runtime, max_runtime) "
                "VALUES (?, ?, ?, ?)",
                (fid, cat["name"], cat.get("min_runtime"), cat.get("max_runtime")),
            )
            category_count += 1

    conn.commit()
    conn.close()

    print(f"Seeded {festival_count} festivals")
    print(f"Seeded {deadline_count} deadlines")
    print(f"Seeded {category_count} categories")


if __name__ == "__main__":
    db_path = os.path.join(os.path.dirname(__file__), "festivals.db")
    # Remove existing DB so we start fresh
    if os.path.exists(db_path):
        os.remove(db_path)
    seed(db_path)
